package br.com.almoxarifado.ativos;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import br.com.almoxarifado.exception.*;
import br.com.almoxarifado.model.*;
import br.com.almoxarifado.obras.*;
import br.com.almoxarifado.repository.*;
import br.com.almoxarifado.security.*;
import jakarta.persistence.EntityManager;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.support.TransactionTemplate;

@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:bes-ativos;MODE=MySQL;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=15000","spring.jpa.properties.hibernate.generate_statistics=true","logging.level.root=WARN","debug=false"})
@ActiveProfiles("test") @AutoConfigureMockMvc
class AtivosTests {
 @Autowired AtivosService service;
 @Autowired AtivoRepository ativos;
 @Autowired RegistroAtivoRepository registros;
 @Autowired FuncionarioRepository pessoas;
 @Autowired AlmoxarifadoRepository locais;
 @Autowired UsuarioRepository usuarios;
 @Autowired AuditoriaRepository eventos;
 @Autowired EstoqueRepository estoques;
 @Autowired MovimentacaoRepository movimentos;
 @Autowired EstruturaService estrutura;
 @Autowired TransactionTemplate tx;
 @Autowired EntityManager em;
 @Autowired MockMvc mvc;
 @MockitoSpyBean AuditoriaService audit;
 Usuario user; Integer ativoId,person,warehouse;
 @BeforeEach void setup(){user=usuarios.save(new Usuario("ativo-"+UUID.randomUUID(),"fixture-hash","Operador H2",Perfil.ADMIN));identity(Perfil.ADMIN);
  var p=new Funcionario();p.setNome("Pessoa H2");p.setMatricula(UUID.randomUUID().toString());person=pessoas.save(p).getId();
  var w=new Almoxarifado();w.setNome("Central H2");warehouse=locais.save(w).getId();ativoId=(Integer)service.criar(criacao(null)).get("id");}
 @AfterEach void cleanup(){reset(audit);SecurityContextHolder.clearContext();}
 void identity(Perfil profile){if(user.getPerfil()!=profile)user=usuarios.save(new Usuario("ativo-"+UUID.randomUUID(),"fixture-hash","H2",profile));SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(new Identidade(user.getId(),user.getUsername(),user.getAuthVersion(),System.currentTimeMillis()),null,profile.permissoes().stream().map(p->new SimpleGrantedAuthority(p.name())).toList()));}
 String key(){return UUID.randomUUID().toString();}
 AtivosInput.Criacao criacao(String codigo){var c=new AtivosInput.Criacao();c.cadastro=new AtivosInput.Cadastro();c.cadastro.nome="Furadeira H2";c.cadastro.codigoPatrimonial=codigo;c.almoxarifadoId=warehouse;c.condicao=CondicaoAtivo.BOM;return c;}
 AtivosInput.Emprestimo loan(){var i=new AtivosInput.Emprestimo();i.ativoId=ativoId;i.entreguePorId=person;i.funcionarioId=person;i.condicao=CondicaoAtivo.BOM;return i;}
 AtivosInput.Devolucao returned(){var i=new AtivosInput.Devolucao();i.devolvidoPorId=person;i.recebidoPorId=person;i.condicao=CondicaoAtivo.BOM;return i;}
 AtivosInput.Transferencia transfer(){var w=new Almoxarifado();w.setNome("Destino H2");var i=new AtivosInput.Transferencia();i.ativoId=ativoId;i.entreguePorId=person;i.almoxarifadoId=locais.save(w).getId();i.condicao=CondicaoAtivo.BOM;return i;}
 AtivosInput.Recebimento arrival(){var i=new AtivosInput.Recebimento();i.recebidoPorId=person;i.condicao=CondicaoAtivo.BOM;return i;}
 AtivosInput.Inspecao inspection(ResultadoInspecao result){var i=new AtivosInput.Inspecao();i.ativoId=ativoId;i.inspetorId=person;i.condicao=result==ResultadoInspecao.REPROVADO?CondicaoAtivo.DANIFICADO:CondicaoAtivo.BOM;i.resultado=result;i.observacao="Conferencia H2";i.proximaInspecao=LocalDate.now().plusDays(30);return i;}
 AtivosInput.Situacao situation(TipoRegistroAtivo tipo){var i=new AtivosInput.Situacao();i.acao=tipo;i.responsavelId=person;i.motivo="Conferencia H2";return i;}
 ObrasInput.Contexto context(){var o=new ObrasInput.Obra();o.codigo="OB-"+key();o.nome="Projeto Alfa";var obra=estrutura.salvarObra(null,o);var c=new ObrasInput.Centro();c.codigo="CC-"+key();c.nome="Centro H2";c.tipo=TipoCentroCusto.OBRA;c.ativo=true;c.obraId=obra.getId();var centro=estrutura.salvarCentro(null,c);var os=new ObrasInput.Ordem();os.obraId=obra.getId();os.centroCustoId=centro.getId();os.titulo="Instalacao";var ordem=estrutura.salvarOrdem(null,os);var ctx=new ObrasInput.Contexto();ctx.obraId=obra.getId();ctx.ordemServicoId=ordem.getId();ctx.centroCustoId=centro.getId();return ctx;}
 AtivosService.Filtro all(){return new AtivosService.Filtro(null,null,null,null,null,null,null,null,null,null,null);}
 @Test void cadastroIndividualNaoAlteraMateriais(){long stock=estoques.count(),mov=movimentos.count();var a=service.buscar(ativoId);assertTrue(a.get("codigoPatrimonial").toString().startsWith("FER-"));assertEquals(StatusAtivo.DISPONIVEL,a.get("status"));assertEquals(stock,estoques.count());assertEquals(mov,movimentos.count());}
 @Test void observacaoMultilinhaPreservadaNoRegistroEReplay(){var l=loan();l.observacao="Conferido na retirada\nMarca preexistente\tsem culpa atribuida";String k=key();var r=service.emprestar(l,k);assertEquals(l.observacao,r.get("observacao"));assertEquals(r.get("id"),service.emprestar(l,k).get("id"));assertThrows(IllegalArgumentException.class,()->AtivosService.texto("nome\nforjado",160,true));assertThrows(IllegalArgumentException.class,()->AtivosService.texto("texto\u0000forjado",2000,false));}
 @Test void baixadoNaoGeraAgendaPendenteNaListaDetalheOuResumo(){tx.executeWithoutResult(t->ativos.findById(ativoId).orElseThrow().proximaInspecao=LocalDate.now());long before=((Number)service.resumo().get("inspecoesPendentes")).longValue();service.situacao(ativoId,situation(TipoRegistroAtivo.BAIXA),key());assertEquals(before-1,((Number)service.resumo().get("inspecoesPendentes")).longValue());assertFalse((Boolean)service.buscar(ativoId).get("inspecaoPendente"));assertFalse(service.listar(new AtivosService.Filtro(null,null,null,null,null,null,null,null,null,null,true),0,100).getContent().stream().anyMatch(a->ativoId.equals(a.get("id"))));}
 @Test void emprestimoParaObraEfetivaLocalEDevolucaoRestauraOrigem(){var l=loan();l.contexto=context();var r=service.emprestar(l,key());assertEquals(warehouse,r.get("localOrigemId"));assertNull(r.get("localDestinoId"));assertNull(service.buscar(ativoId).get("almoxarifadoId"));assertEquals(l.contexto.obraId,((ContextoOperacional)service.buscar(ativoId).get("contexto")).getObraId());service.devolver((Integer)r.get("id"),returned(),key());assertEquals(warehouse,service.buscar(ativoId).get("almoxarifadoId"));assertNull(service.buscar(ativoId).get("contexto"));}
 @Test void pesquisaTrataSublinhadoComoTextoLiteral(){var one=service.criar(criacao("TAG_A"));service.criar(criacao("TAGXA"));var page=service.listar(new AtivosService.Filtro("TAG_A",null,null,null,null,null,null,null,null,null,null),0,20);assertEquals(1,page.getTotalElements());assertEquals(one.get("id"),page.getContent().get(0).get("id"));}
 @Test void observacaoLiteralNullNaoColideComAusenciaNaChave(){var l=loan();String k=key();service.emprestar(l,k);l.observacao="<null>";assertThrows(ConflitoException.class,()->service.emprestar(l,k));}
 @Test void filtrosAbertoEVencidoContraditoriosNaoIgnoramFechado(){var l=loan();int id=(Integer)service.emprestar(l,key()).get("id");tx.executeWithoutResult(t->em.createNativeQuery("update bes_registro_ativo set previsao_devolucao=:d where id=:id").setParameter("d",LocalDate.now().minusDays(1)).setParameter("id",id).executeUpdate());assertEquals(0,service.listarRegistros(TipoRegistroAtivo.EMPRESTIMO,ativoId,null,null,null,null,false,true,null,null,0,20).getTotalElements());}
 @Test void inspecaoConcluidaNaoPrecisaEventoDeEncerramento(){service.inspecionar(inspection(ResultadoInspecao.APROVADO),key());assertEquals(1,service.listarRegistros(TipoRegistroAtivo.INSPECAO,ativoId,null,null,null,null,false,null,null,null,0,20).getTotalElements());}
 @Test void historicoEReplayPreservamCamposComProxiesNoContexto(){var command=loan();String chave=key();Integer id=(Integer)service.emprestar(command,chave).get("id");tx.executeWithoutResult(t->{em.getReference(Ativo.class,ativoId);em.getReference(RegistroAtivo.class,id);var h=service.historico(ativoId,0,20).getContent().get(0);assertEquals(id,h.get("id"));assertEquals(TipoRegistroAtivo.EMPRESTIMO,h.get("tipo"));assertEquals(person,h.get("recebidoPorId"));assertEquals(id,service.emprestar(command,chave).get("id"));assertEquals(StatusAtivo.EMPRESTADO,service.buscar(ativoId).get("status"));});}
 @Test void codigoManualNormalizadoUnicoEImutavel(){var c=criacao(" tag-abc ");var a=service.criar(c);assertEquals("TAG-ABC",a.get("codigoPatrimonial"));assertThrows(org.springframework.dao.DataIntegrityViolationException.class,()->service.criar(criacao("TAG-ABC")));var edit=c.cadastro;edit.codigoPatrimonial="OUTRO";assertThrows(ConflitoException.class,()->service.editar((Integer)a.get("id"),edit));}
 @Test void prefixoAutomaticoReservado(){assertThrows(IllegalArgumentException.class,()->service.criar(criacao("FER-000001")));}
 @ParameterizedTest @EnumSource(CondicaoAtivo.class) void condicaoInicialDefineDisponibilidade(CondicaoAtivo c){var in=criacao(null);in.condicao=c;var a=service.criar(in);assertEquals(c.utilizavel()?StatusAtivo.DISPONIVEL:StatusAtivo.INDISPONIVEL,a.get("status"));}
 @Test void cicloEmprestimoDevolucaoComHistoricoEAtor(){var l=service.emprestar(loan(),key());int id=(Integer)l.get("id");assertEquals(user.getId(),l.get("atorId"));assertEquals(person,l.get("recebidoPorId"));assertEquals(person,service.buscar(ativoId).get("responsavelId"));assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));var ret=returned();ret.observacao="Avaria relatada sem atribuir culpa";ret.condicao=CondicaoAtivo.REGULAR;service.devolver(id,ret,key());assertEquals(StatusAtivo.DISPONIVEL,service.buscar(ativoId).get("status"));assertNull(service.buscar(ativoId).get("responsavelId"));assertEquals(2,service.historico(ativoId,0,20).getTotalElements());assertNotNull(service.buscarRegistro(id,TipoRegistroAtivo.EMPRESTIMO).get("encerramento"));assertFalse((Boolean)service.buscarRegistro(id,TipoRegistroAtivo.EMPRESTIMO).get("aberto"));}
 @Test void danoNaDevolucaoBloqueiaNovaRetirada(){int id=(Integer)service.emprestar(loan(),key()).get("id");var r=returned();r.condicao=CondicaoAtivo.DANIFICADO;service.devolver(id,r,key());assertEquals(StatusAtivo.INDISPONIVEL,service.buscar(ativoId).get("status"));assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));}
 @Test void devolucaoRepetidaChaveDiferenteConflito(){int id=(Integer)service.emprestar(loan(),key()).get("id");service.devolver(id,returned(),key());assertThrows(ConflitoException.class,()->service.devolver(id,returned(),key()));}
 @Test void chavesPersistidasRepetemSemNovoEfeito(){String k=key();var in=loan();var one=service.emprestar(in,k);assertEquals(one.get("id"),service.emprestar(in,k).get("id"));String kr=key();var r=returned();var two=service.devolver((Integer)one.get("id"),r,kr);assertEquals(two.get("id"),service.devolver((Integer)one.get("id"),r,kr).get("id"));assertEquals(one.get("id"),service.emprestar(in,k).get("id"));in.observacao="Outro payload";assertThrows(ConflitoException.class,()->service.emprestar(in,k));assertEquals(2,service.historico(ativoId,0,20).getTotalElements());}
 @Test void transferenciaExigeChegadaPreservaCondicoes(){var t=transfer();String k=key();var sent=service.transferir(t,k);assertEquals(sent.get("id"),service.transferir(t,k).get("id"));assertEquals(warehouse,service.buscar(ativoId).get("almoxarifadoId"));assertEquals(StatusAtivo.EM_TRANSFERENCIA,service.buscar(ativoId).get("status"));assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));var in=arrival();in.condicao=CondicaoAtivo.DANIFICADO;in.observacao="Dano percebido na chegada";String kr=key();var arrived=service.receber((Integer)sent.get("id"),in,kr);assertEquals(arrived.get("id"),service.receber((Integer)sent.get("id"),in,kr).get("id"));assertEquals(t.almoxarifadoId,service.buscar(ativoId).get("almoxarifadoId"));assertEquals(StatusAtivo.INDISPONIVEL,service.buscar(ativoId).get("status"));assertThrows(ConflitoException.class,()->service.receber((Integer)sent.get("id"),in,key()));assertEquals(CondicaoAtivo.BOM,sent.get("condicaoDepois"));assertEquals(CondicaoAtivo.DANIFICADO,arrived.get("condicaoDepois"));}
 @Test void transferenciaObraOsHistoricoResisteRenomeacao(){var ctx=context();var t=transfer();t.almoxarifadoId=null;t.contexto=ctx;int sent=(Integer)service.transferir(t,key()).get("id");var o=new ObrasInput.Obra();o.codigo=estrutura.obra(ctx.obraId).getCodigo();o.nome="Projeto Alfa Revisado";estrutura.salvarObra(ctx.obraId,o);service.receber(sent,arrival(),key());var a=service.buscar(ativoId);assertEquals("Projeto Alfa",((ContextoOperacional)a.get("contexto")).getObraNome());var l=loan();l.contexto=ctx;int id=(Integer)service.emprestar(l,key()).get("id");service.devolver(id,returned(),key());assertEquals(ctx.obraId,((ContextoOperacional)service.buscar(ativoId).get("contexto")).getObraId());var back=transfer();back.almoxarifadoId=warehouse;service.receber((Integer)service.transferir(back,key()).get("id"),arrival(),key());assertNull(service.buscar(ativoId).get("contexto"));assertEquals(6,service.historico(ativoId,0,20).getTotalElements());}
 @Test void outraObraExigeTransferenciaFisica(){var a=context();var b=context();var t=transfer();t.almoxarifadoId=null;t.contexto=a;service.receber((Integer)service.transferir(t,key()).get("id"),arrival(),key());var l=loan();l.contexto=b;assertThrows(ConflitoException.class,()->service.emprestar(l,key()));}
 @Test void idsContextuaisIncompativeisRecusados(){var a=context();var b=context();a.obraId=b.obraId;var in=loan();in.contexto=a;assertThrows(ConflitoException.class,()->service.emprestar(in,key()));assertEquals(StatusAtivo.DISPONIVEL,service.buscar(ativoId).get("status"));}
 @Test void centroCorporativoValidoSemObra(){var c=new ObrasInput.Centro();c.codigo="CC-"+key();c.nome="Corporativo";c.tipo=TipoCentroCusto.ADMINISTRATIVO;c.ativo=true;var cc=estrutura.salvarCentro(null,c);var in=loan();in.contexto=new ObrasInput.Contexto();in.contexto.centroCustoId=cc.getId();var l=service.emprestar(in,key());var ctx=(ContextoOperacional)l.get("contextoDestino");assertNull(ctx.getObraId());assertEquals(cc.getId(),ctx.getCentroCustoId());}
 @Test void referenciaFuncionarioInexistenteReverte(){var l=loan();l.funcionarioId=Integer.MAX_VALUE;assertThrows(RecursoNaoEncontradoException.class,()->service.emprestar(l,key()));assertEquals(StatusAtivo.DISPONIVEL,service.buscar(ativoId).get("status"));assertEquals(0,service.historico(ativoId,0,20).getTotalElements());}
 @Test void reprovacaoEReinspecaoControlamDisponibilidade(){var i=inspection(ResultadoInspecao.REPROVADO);String k=key();var r=service.inspecionar(i,k);assertEquals(r.get("id"),service.inspecionar(i,k).get("id"));assertEquals(StatusAtivo.INDISPONIVEL,service.buscar(ativoId).get("status"));assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));service.inspecionar(inspection(ResultadoInspecao.APROVADO),key());service.emprestar(loan(),key());}
 @Test void reprovacaoDuranteCustodiaNaoApagaResponsavel(){int id=(Integer)service.emprestar(loan(),key()).get("id");service.inspecionar(inspection(ResultadoInspecao.REPROVADO),key());assertEquals(StatusAtivo.EMPRESTADO,service.buscar(ativoId).get("status"));assertEquals(person,service.buscar(ativoId).get("responsavelId"));service.devolver(id,returned(),key());assertEquals(StatusAtivo.INDISPONIVEL,service.buscar(ativoId).get("status"));}
 @Test void aprovacaoIncompativelComDanoRecusada(){var i=inspection(ResultadoInspecao.APROVADO);i.condicao=CondicaoAtivo.INOPERANTE;assertThrows(ConflitoException.class,()->service.inspecionar(i,key()));}
 @Test void agendaInspecaoVencidaBloqueiaEmprestimo(){tx.executeWithoutResult(t->{var a=ativos.findById(ativoId).orElseThrow();a.proximaInspecao=LocalDate.now();});assertTrue((Boolean)service.buscar(ativoId).get("inspecaoPendente"));assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));service.inspecionar(inspection(ResultadoInspecao.APROVADO),key());service.emprestar(loan(),key());}
 @Test void inativacaoBaixaSemDeleteEComMotivo(){service.situacao(ativoId,situation(TipoRegistroAtivo.INATIVACAO),key());assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));assertThrows(ConflitoException.class,()->service.transferir(transfer(),key()));service.situacao(ativoId,situation(TipoRegistroAtivo.REATIVACAO),key());service.situacao(ativoId,situation(TipoRegistroAtivo.BAIXA),key());assertEquals(StatusAtivo.BAIXADO,service.buscar(ativoId).get("status"));assertThrows(ConflitoException.class,()->service.situacao(ativoId,situation(TipoRegistroAtivo.REATIVACAO),key()));assertEquals(3,service.historico(ativoId,0,20).getTotalElements());}
 @Test void baixaDuranteCustodiaBloqueada(){service.emprestar(loan(),key());assertThrows(ConflitoException.class,()->service.situacao(ativoId,situation(TipoRegistroAtivo.BAIXA),key()));}
 @Test void filtrosNaoMisturamContextsEProdutoLegadoNaoExigeAtivo(){var ctx=context();var l=loan();l.contexto=ctx;service.emprestar(l,key());assertEquals(1,service.listar(new AtivosService.Filtro(null,null,null,null,person,null,ctx.obraId,ctx.ordemServicoId,ctx.centroCustoId,null,null),0,20).getTotalElements());assertEquals(0,service.listar(new AtivosService.Filtro(null,null,null,null,null,null,ctx.obraId,Integer.MAX_VALUE,null,null,null),0,20).getTotalElements());assertNotNull(service.buscar(ativoId));}
 @Test void emprestimosVencidosSaoSomenteAbertos(){var l=loan();l.previsaoDevolucao=LocalDate.now();int id=(Integer)service.emprestar(l,key()).get("id");tx.executeWithoutResult(t->em.createNativeQuery("update bes_registro_ativo set previsao_devolucao=:d where id=:id").setParameter("d",LocalDate.now().minusDays(1)).setParameter("id",id).executeUpdate());assertTrue((Boolean)service.buscarRegistro(id,TipoRegistroAtivo.EMPRESTIMO).get("vencido"));assertTrue(((Number)service.resumo().get("emprestimosVencidos")).longValue()>0);service.devolver(id,returned(),key());assertFalse((Boolean)service.buscarRegistro(id,TipoRegistroAtivo.EMPRESTIMO).get("vencido"));}
 @Test void auditRollbackReverteCustodiaEventoEChave(){long before=registros.count(),auditCount=eventos.count();tx.executeWithoutResult(t->doThrow(new IllegalStateException("falha H2")).when(audit).registrar(eq("ATIVO_EMPRESTIMO"),anyString(),anyString(),any(),any(),any()));assertThrows(IllegalStateException.class,()->service.emprestar(loan(),key()));assertEquals(StatusAtivo.DISPONIVEL,service.buscar(ativoId).get("status"));assertNull(service.buscar(ativoId).get("pendenciaId"));assertEquals(before,registros.count());assertEquals(auditCount,eventos.count());}
 @ParameterizedTest @EnumSource(Perfil.class) void matrizServiceEHttp(Perfil profile)throws Exception{identity(profile);assertNotNull(service.buscar(ativoId));mvc.perform(get("/ativos").with(authentication(SecurityContextHolder.getContext().getAuthentication()))).andExpect(status().isOk());identity(profile);if(profile==Perfil.CONSULTA){assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.emprestar(loan(),key()));assertNotNull(service.listarRegistros(TipoRegistroAtivo.INSPECAO,null,null,null,null,null,null,null,null,null,0,20));
 }else service.emprestar(loan(),key());if(profile==Perfil.CONSULTA||profile==Perfil.ALMOXARIFE)assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.criar(criacao(null)));else assertNotNull(service.criar(criacao(null)));}
 @ParameterizedTest @ValueSource(strings={"/ativos","/emprestimos","/transferencias-ativos","/inspecoes-ativos","/emprestimos/1/devolucao","/transferencias-ativos/1/recebimento"}) void csrfObrigatorio(String path)throws Exception{mvc.perform(post(path).with(authentication(SecurityContextHolder.getContext().getAuthentication())).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isForbidden());}
 @ParameterizedTest @ValueSource(strings={"atorId","status","criadoEm","condicaoAntes","contextoOrigem","pendenciaId"}) void massAssignmentRejeitado(String field)throws Exception{mvc.perform(post("/emprestimos").with(authentication(SecurityContextHolder.getContext().getAuthentication())).with(csrf()).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content("{\""+field+"\":\"forjado\"}")).andExpect(status().isBadRequest());}
 @Test void idorTipoDeRegistroNaoContornaOperacao(){int id=(Integer)service.emprestar(loan(),key()).get("id");assertThrows(ConflitoException.class,()->service.receber(id,arrival(),key()));assertThrows(RecursoNaoEncontradoException.class,()->service.buscarRegistro(id,TipoRegistroAtivo.TRANSFERENCIA));identity(Perfil.CONSULTA);assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.devolver(id,returned(),key()));}
 @Test void semAuthorityDiretaRejeitaTodasEscritas(){SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken("sem-authority","",List.of()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.criar(criacao(null)));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.editar(ativoId,criacao(null).cadastro));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.situacao(ativoId,situation(TipoRegistroAtivo.BAIXA),key()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.devolver(1,returned(),key()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.receber(1,arrival(),key()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.emprestar(loan(),key()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.transferir(transfer(),key()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.inspecionar(inspection(ResultadoInspecao.APROVADO),key()));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.listarRegistros(TipoRegistroAtivo.EMPRESTIMO,null,null,null,null,null,null,null,null,null,0,20));}
 @Test void listagensEHistoricoSemNMaisUm(){var stats=em.getEntityManagerFactory().unwrap(org.hibernate.SessionFactory.class).getStatistics();service.emprestar(loan(),key());stats.clear();service.listar(all(),0,100);long one=stats.getPrepareStatementCount();for(int i=0;i<12;i++)service.criar(criacao(null));stats.clear();service.listar(all(),0,100);assertTrue(stats.getPrepareStatementCount()<=one+1);stats.clear();service.historico(ativoId,0,20);assertTrue(stats.getPrepareStatementCount()<=4);}
 boolean run(Callable<?> task,org.springframework.security.core.Authentication auth,CountDownLatch start)throws Exception{SecurityContextHolder.getContext().setAuthentication(auth);try{start.await();task.call();return true;}catch(ConflitoException|org.springframework.dao.DataIntegrityViolationException e){return false;}finally{SecurityContextHolder.clearContext();}}
 void race(Callable<?> one,Callable<?> two)throws Exception{var auth=SecurityContextHolder.getContext().getAuthentication();var start=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{var a=pool.submit(()->run(one,auth,start));var b=pool.submit(()->run(two,auth,start));start.countDown();assertNotEquals(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS));}finally{pool.shutdownNow();}}
 @Test void emprestimosConcorrentesTemUmVencedor()throws Exception{race(()->service.emprestar(loan(),key()),()->service.emprestar(loan(),key()));assertEquals(1,service.historico(ativoId,0,20).getTotalElements());}
 @Test void devolucoesConcorrentesTemUmVencedor()throws Exception{int id=(Integer)service.emprestar(loan(),key()).get("id");race(()->service.devolver(id,returned(),key()),()->service.devolver(id,returned(),key()));assertEquals(2,service.historico(ativoId,0,20).getTotalElements());}
 @Test void emprestimoVsTransferenciaTemUmVencedor()throws Exception{var t=transfer();race(()->service.emprestar(loan(),key()),()->service.transferir(t,key()));assertEquals(1,service.historico(ativoId,0,20).getTotalElements());}
 @Test void codigoManualConcorrenteUniqueObrigatorio()throws Exception{String codigo="H2-"+key();race(()->service.criar(criacao(codigo)),()->service.criar(criacao(codigo)));}
 @Test void codigosAutomaticosConcorrentesDistintos()throws Exception{var auth=SecurityContextHolder.getContext().getAuthentication();var pool=Executors.newFixedThreadPool(2);try{Callable<String> create=()->{SecurityContextHolder.getContext().setAuthentication(auth);try{return service.criar(criacao(null)).get("codigoPatrimonial").toString();}finally{SecurityContextHolder.clearContext();}};var a=pool.submit(create);var b=pool.submit(create);assertNotEquals(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS));}finally{pool.shutdownNow();}}
 @Test void transferenciasConcorrentesDestinosDistintosTemUmVencedor()throws Exception{var a=transfer();var b=transfer();race(()->service.transferir(a,key()),()->service.transferir(b,key()));assertEquals(1,service.historico(ativoId,0,20).getTotalElements());assertEquals(StatusAtivo.EM_TRANSFERENCIA,service.buscar(ativoId).get("status"));assertEquals(warehouse,service.buscar(ativoId).get("almoxarifadoId"));}
 @Test void chegadasConcorrentesNaoDuplicamHistorico()throws Exception{var t=transfer();int id=(Integer)service.transferir(t,key()).get("id");race(()->service.receber(id,arrival(),key()),()->service.receber(id,arrival(),key()));assertEquals(2,service.historico(ativoId,0,20).getTotalElements());assertEquals(t.almoxarifadoId,service.buscar(ativoId).get("almoxarifadoId"));assertNull(service.buscar(ativoId).get("pendenciaId"));}
 @Test void mesmaChaveConcorrenteRetornaMesmoRegistro()throws Exception{var auth=SecurityContextHolder.getContext().getAuthentication();String k=key();var start=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{Callable<Object> task=()->{SecurityContextHolder.getContext().setAuthentication(auth);try{start.await();return service.emprestar(loan(),k).get("id");}finally{SecurityContextHolder.clearContext();}};var a=pool.submit(task);var b=pool.submit(task);start.countDown();assertEquals(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS));assertEquals(1,service.historico(ativoId,0,20).getTotalElements());}finally{pool.shutdownNow();}}
 @ParameterizedTest @EnumSource(value=TipoRegistroAtivo.class,names={"TRANSFERENCIA","RECEBIMENTO","DEVOLUCAO","INSPECAO","BAIXA"}) void rollbackTodosEventosCriticos(TipoRegistroAtivo type){Integer origem=type==TipoRegistroAtivo.DEVOLUCAO?(Integer)service.emprestar(loan(),key()).get("id"):type==TipoRegistroAtivo.RECEBIMENTO?(Integer)service.transferir(transfer(),key()).get("id"):null;var before=service.buscar(ativoId);long events=registros.count(),audits=eventos.count();String k=key();var t=type==TipoRegistroAtivo.TRANSFERENCIA?transfer():null;tx.executeWithoutResult(x->doThrow(new IllegalStateException("falha H2")).when(audit).registrar(eq("ATIVO_"+type),anyString(),anyString(),any(),any(),any()));assertThrows(IllegalStateException.class,()->{switch(type){case TRANSFERENCIA->service.transferir(t,k);case RECEBIMENTO->service.receber(origem,arrival(),k);case DEVOLUCAO->service.devolver(origem,returned(),k);case INSPECAO->service.inspecionar(inspection(ResultadoInspecao.REPROVADO),k);case BAIXA->service.situacao(ativoId,situation(TipoRegistroAtivo.BAIXA),k);default->throw new AssertionError();}});assertEquals(before,service.buscar(ativoId));assertEquals(events,registros.count());assertEquals(audits,eventos.count());assertTrue(registros.findByChaveIdempotencia(k).isEmpty());}
 @Test void destinoInexistenteOuDuploNaoAlteraAtivo(){var t=transfer();t.almoxarifadoId=Integer.MAX_VALUE;assertThrows(RecursoNaoEncontradoException.class,()->service.transferir(t,key()));t.contexto=context();t.almoxarifadoId=warehouse;assertThrows(IllegalArgumentException.class,()->service.transferir(t,key()));int id=(Integer)service.emprestar(loan(),key()).get("id");var r=returned();r.almoxarifadoId=Integer.MAX_VALUE;assertThrows(RecursoNaoEncontradoException.class,()->service.devolver(id,r,key()));assertEquals(StatusAtivo.EMPRESTADO,service.buscar(ativoId).get("status"));assertEquals(1,service.historico(ativoId,0,20).getTotalElements());}
 @Test void estadosEIdsIncompativeisRejeitadosSemEfeito(){assertThrows(RecursoNaoEncontradoException.class,()->service.devolver(Integer.MAX_VALUE,returned(),key()));assertThrows(RecursoNaoEncontradoException.class,()->service.receber(Integer.MAX_VALUE,arrival(),key()));var i=inspection(ResultadoInspecao.APROVADO);i.ativoId=Integer.MAX_VALUE;assertThrows(RecursoNaoEncontradoException.class,()->service.inspecionar(i,key()));int id=(Integer)service.transferir(transfer(),key()).get("id");assertThrows(ConflitoException.class,()->service.devolver(id,returned(),key()));assertThrows(ConflitoException.class,()->service.inspecionar(inspection(ResultadoInspecao.APROVADO),key()));service.receber(id,arrival(),key());service.situacao(ativoId,situation(TipoRegistroAtivo.BAIXA),key());assertThrows(ConflitoException.class,()->service.emprestar(loan(),key()));assertThrows(ConflitoException.class,()->service.transferir(transfer(),key()));assertThrows(ConflitoException.class,()->service.inspecionar(inspection(ResultadoInspecao.APROVADO),key()));assertEquals(3,service.historico(ativoId,0,20).getTotalElements());}
 @Test void historicosMultiplosNaoMultiplicamAtivoOuDashboard(){long before=((Number)service.resumo().get("emprestimosAbertos")).longValue();for(int j=0;j<3;j++)service.devolver((Integer)service.emprestar(loan(),key()).get("id"),returned(),key());service.emprestar(loan(),key());assertEquals(before+1,((Number)service.resumo().get("emprestimosAbertos")).longValue());assertEquals(1,service.listar(new AtivosService.Filtro((String)service.buscar(ativoId).get("codigoPatrimonial"),null,null,null,null,null,null,null,null,null,null),0,20).getTotalElements());var list=service.listarRegistros(TipoRegistroAtivo.EMPRESTIMO,ativoId,null,null,null,null,true,null,null,null,0,20);assertEquals(1,list.getTotalElements());assertTrue((Boolean)list.getContent().get(0).get("aberto"));assertEquals(7,service.historico(ativoId,0,20).getTotalElements());}
 @Test void todasConsultasMantemNumeroConstanteDeQueries(){var stats=em.getEntityManagerFactory().unwrap(org.hibernate.SessionFactory.class).getStatistics();stats.clear();service.resumo();long dashboardQueries=stats.getPrepareStatementCount();for(int j=0;j<15;j++)service.inspecionar(inspection(ResultadoInspecao.APROVADO),key());for(var tipo:List.of(TipoRegistroAtivo.EMPRESTIMO,TipoRegistroAtivo.TRANSFERENCIA,TipoRegistroAtivo.INSPECAO)){stats.clear();service.listarRegistros(tipo,null,null,null,null,null,null,null,null,null,0,100);assertTrue(stats.getPrepareStatementCount()<=4,"N+1 em "+tipo);}stats.clear();service.historico(ativoId,0,100);assertTrue(stats.getPrepareStatementCount()<=4);stats.clear();service.buscar(ativoId);assertTrue(stats.getPrepareStatementCount()<=2);stats.clear();service.resumo();assertEquals(dashboardQueries,stats.getPrepareStatementCount());}
 @ParameterizedTest @EnumSource(Perfil.class) void matrizHttpTodos18HandlersComPayloadReal(Perfil perfil)throws Exception{
  int loanId=(Integer)service.emprestar(loan(),key()).get("id");int transferAsset=(Integer)service.criar(criacao(null)).get("id");var transfer=transfer();transfer.ativoId=transferAsset;int transferId=(Integer)service.transferir(transfer,key()).get("id");int available=(Integer)service.criar(criacao(null)).get("id");var inspect=inspection(ResultadoInspecao.APROVADO);inspect.ativoId=available;int inspectionId=(Integer)service.inspecionar(inspect,key()).get("id");String code=(String)service.buscar(available).get("codigoPatrimonial");
  identity(perfil);var authentication=SecurityContextHolder.getContext().getAuthentication();for(String path:List.of("/ativos","/ativos/resumo","/ativos/"+ativoId,"/ativos/"+ativoId+"/historico","/emprestimos","/emprestimos/"+loanId,"/transferencias-ativos","/transferencias-ativos/"+transferId,"/inspecoes-ativos","/inspecoes-ativos/"+inspectionId))mvc.perform(get(path).with(authentication(authentication))).andExpect(status().isOk());
  var inputs=List.of(new String[]{"POST","/ativos","{\"cadastro\":{\"nome\":\"Ativo HTTP H2\"},\"almoxarifadoId\":"+warehouse+",\"condicao\":\"BOM\"}","ATIVO_GERENCIAR"},new String[]{"PUT","/ativos/"+available,"{\"codigoPatrimonial\":\""+code+"\",\"nome\":\"Ativo editado HTTP\"}","ATIVO_GERENCIAR"},new String[]{"POST","/emprestimos","{\"ativoId\":"+available+",\"entreguePorId\":"+person+",\"funcionarioId\":"+person+",\"condicao\":\"BOM\"}","EMPRESTIMO_GERENCIAR"},new String[]{"POST","/emprestimos/"+loanId+"/devolucao","{\"devolvidoPorId\":"+person+",\"recebidoPorId\":"+person+",\"condicao\":\"BOM\"}","EMPRESTIMO_GERENCIAR"},new String[]{"POST","/transferencias-ativos","{\"ativoId\":"+ativoId+",\"entreguePorId\":"+person+",\"almoxarifadoId\":"+transfer.almoxarifadoId+",\"condicao\":\"BOM\"}","TRANSFERENCIA_ATIVO_GERENCIAR"},new String[]{"POST","/transferencias-ativos/"+transferId+"/recebimento","{\"recebidoPorId\":"+person+",\"condicao\":\"BOM\"}","TRANSFERENCIA_ATIVO_GERENCIAR"},new String[]{"POST","/inspecoes-ativos","{\"ativoId\":"+available+",\"inspetorId\":"+person+",\"condicao\":\"BOM\",\"resultado\":\"APROVADO\"}","INSPECAO_ATIVO_GERENCIAR"},new String[]{"PUT","/ativos/"+transferAsset+"/situacao","{\"acao\":\"INATIVACAO\",\"responsavelId\":"+person+",\"motivo\":\"Registro HTTP H2\"}","ATIVO_GERENCIAR"});
  for(var input:inputs){var request=input[0].equals("POST")?post(input[1]):put(input[1]);int expected=perfil.permissoes().contains(Permissao.valueOf(input[3]))?200:403;mvc.perform(request.with(authentication(authentication)).with(csrf()).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content(input[2])).andExpect(status().is(expected));}
 }
 @ParameterizedTest @ValueSource(strings={"/ativos/1","/ativos/1/situacao"}) void csrfTambemProtegePut(String path)throws Exception{mvc.perform(put(path).with(authentication(SecurityContextHolder.getContext().getAuthentication())).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isForbidden());}
 @ParameterizedTest @ValueSource(strings={"/ativos","/ativos/1","/ativos/1/situacao","/emprestimos","/emprestimos/1/devolucao","/transferencias-ativos","/transferencias-ativos/1/recebimento","/inspecoes-ativos"}) void forjaCamposHistoricosEmTodosMutadores(String path)throws Exception{var request=path.equals("/ativos/1")||path.endsWith("/situacao")?put(path):post(path);mvc.perform(request.with(authentication(SecurityContextHolder.getContext().getAuthentication())).with(csrf()).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content("{\"atorId\":999,\"status\":\"DISPONIVEL\",\"contextoOrigem\":{\"obraId\":999}}")).andExpect(status().isBadRequest());}
 @Test void contextoForjadoNoDtoRejeitado()throws Exception{mvc.perform(post("/emprestimos").with(authentication(SecurityContextHolder.getContext().getAuthentication())).with(csrf()).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content("{\"contexto\":{\"obraNome\":\"forjado\"}}")).andExpect(status().isBadRequest());}
}
