-- PostgreSQL: proposta para schema equivalente futuro, não migra dados MySQL.
-- Verificar compatibilidade dos IDs/FKs e usar transação DDL em homologação.
-- BLOCO 3: proposta manual, não executada pela aplicação nem nesta rodada.
-- Aplicar somente após backup e homologação do schema real. Não é idempotente.
-- Requer Blocos 1/2 e estoque único por produto + almoxarifado. Não executar em produção sem revisão.
-- Não altera saldos nem status antigos, não reconstrói quantidades e não remove histórico.
-- Inspecionar primeiro os tipos/constraints da coluna solicitacao.status:
-- se for ENUM/CHECK limitado aos estados antigos, ampliar a lista preservando os estados existentes
-- para PENDENTE, APROVADA, EM_SEPARACAO, PARCIALMENTE_ATENDIDA, ATENDIDA, REJEITADA.
-- A sintaxe específica depende do DDL real; não executar DROP genérico de constraints.
SELECT id, status FROM solicitacao;
SELECT id, solicitacao_id, produto_id, quantidade FROM item_solicitacao WHERE quantidade <= 0;
SELECT solicitacao_id, produto_id, SUM(quantidade) AS saida_legada
FROM movimentacao WHERE solicitacao_id IS NOT NULL AND tipo = 'SAIDA'
GROUP BY solicitacao_id, produto_id;
-- Verificar previamente se colunas, tabelas e índices abaixo já existem.

ALTER TABLE solicitacao ADD COLUMN responsavel_aprovacao_id INT NULL;
ALTER TABLE solicitacao ADD COLUMN data_aprovacao TIMESTAMP(6) NULL;
ALTER TABLE solicitacao ADD COLUMN responsavel_separacao_id INT NULL;
ALTER TABLE solicitacao ADD COLUMN data_separacao TIMESTAMP(6) NULL;
ALTER TABLE solicitacao ADD CONSTRAINT fk_solic_aprovador FOREIGN KEY (responsavel_aprovacao_id) REFERENCES funcionario(id);
ALTER TABLE solicitacao ADD CONSTRAINT fk_solic_separador FOREIGN KEY (responsavel_separacao_id) REFERENCES funcionario(id);
ALTER TABLE item_solicitacao ADD COLUMN quantidade_atendida DOUBLE PRECISION NULL;
-- NULL representa legado a conferir, nunca substituir indiscriminadamente por zero.
ALTER TABLE item_solicitacao ADD CONSTRAINT ck_item_solic_atendida CHECK (quantidade_atendida IS NULL OR (quantidade_atendida >= 0 AND quantidade_atendida <= quantidade));

CREATE TABLE atendimento_solicitacao (
 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 solicitacao_id INT NOT NULL,
 responsavel_id INT NOT NULL,
 data_hora TIMESTAMP(6) NOT NULL,
 chave_idempotencia VARCHAR(100) COLLATE "C" NOT NULL,
 assinatura_payload VARCHAR(64) NOT NULL,
 CONSTRAINT uk_atendimento_chave UNIQUE (chave_idempotencia),
 CONSTRAINT fk_atendimento_solic FOREIGN KEY (solicitacao_id) REFERENCES solicitacao(id),
 CONSTRAINT fk_atendimento_resp FOREIGN KEY (responsavel_id) REFERENCES funcionario(id)
);
CREATE INDEX ix_atendimento_solic ON atendimento_solicitacao(solicitacao_id);

CREATE TABLE item_atendimento_solicitacao (
 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 atendimento_id INT NOT NULL,
 item_solicitacao_id INT NOT NULL,
 quantidade DOUBLE PRECISION NOT NULL,
 CONSTRAINT uk_atendimento_item UNIQUE (atendimento_id, item_solicitacao_id),
 CONSTRAINT fk_item_atendimento FOREIGN KEY (atendimento_id) REFERENCES atendimento_solicitacao(id),
 CONSTRAINT fk_item_atendido_solic FOREIGN KEY (item_solicitacao_id) REFERENCES item_solicitacao(id),
 CONSTRAINT ck_item_atendido_quantidade CHECK (quantidade > 0)
);
ALTER TABLE movimentacao ADD COLUMN atendimento_id INT NULL;
ALTER TABLE movimentacao ADD CONSTRAINT fk_mov_atendimento FOREIGN KEY (atendimento_id) REFERENCES atendimento_solicitacao(id);
CREATE INDEX ix_mov_atendimento ON movimentacao(atendimento_id);

CREATE TABLE necessidade_compra (
 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_solicitacao_id INT NOT NULL,
 solicitacao_id INT NOT NULL,
 produto_id INT NOT NULL,
 almoxarifado_id INT NOT NULL,
 responsavel_id INT NOT NULL,
 quantidade DOUBLE PRECISION NOT NULL,
 status VARCHAR(30) NOT NULL,
 data_hora TIMESTAMP(6) NOT NULL,
 motivo VARCHAR(100) NOT NULL,
 chave_idempotencia VARCHAR(100) COLLATE "C" NOT NULL,
 assinatura_payload VARCHAR(64) NOT NULL,
 CONSTRAINT uk_necessidade_item UNIQUE (item_solicitacao_id),
 CONSTRAINT uk_necessidade_chave UNIQUE (chave_idempotencia),
 CONSTRAINT fk_necessidade_item FOREIGN KEY (item_solicitacao_id) REFERENCES item_solicitacao(id),
 CONSTRAINT fk_necessidade_solic FOREIGN KEY (solicitacao_id) REFERENCES solicitacao(id),
 CONSTRAINT fk_necessidade_prod FOREIGN KEY (produto_id) REFERENCES produto(id),
 CONSTRAINT fk_necessidade_local FOREIGN KEY (almoxarifado_id) REFERENCES almoxarifado(id),
 CONSTRAINT fk_necessidade_resp FOREIGN KEY (responsavel_id) REFERENCES funcionario(id),
 CONSTRAINT ck_necessidade_quantidade CHECK (quantidade > 0),
 CONSTRAINT ck_necessidade_status CHECK (status IN ('ABERTA','ATENDIDA','CANCELADA'))
);
CREATE INDEX ix_necessidade_solic ON necessidade_compra(solicitacao_id);
CREATE INDEX ix_necessidade_filtros ON necessidade_compra(status, produto_id, almoxarifado_id);
