-- BLOCO 2: preparação manual, NÃO executada pela aplicação.
-- Revisar backup, schema real, versões e constraints antes de aplicar UMA ÚNICA VEZ.
-- Pré-requisitos: Bloco 1 aplicado; IDs legados INT; par estoque único já protegido.
-- PostgreSQL: proposta para schema equivalente futuro, não migra dados do MySQL.
-- MySQL: 8.0.16+ para enforcement de CHECK; DDL faz commit implícito.
-- Nenhum DROP, DELETE, TRUNCATE, saldo regravado ou consolidação de duplicatas.

-- Auditoria read-only: interromper preparação se houver linhas nestas consultas.
SELECT produto_id, almoxarifado_id, COUNT(*) AS registros
FROM estoque GROUP BY produto_id, almoxarifado_id HAVING COUNT(*) > 1;
SELECT id FROM estoque WHERE produto_id IS NULL OR almoxarifado_id IS NULL OR quantidade < 0;
-- Inspecionar também se colunas/tabelas/índices abaixo já existem: script não é idempotente.
-- A constraint uk_estoque_produto_almoxarifado deve existir antes da nova API.
-- Se ausente, usar estoque-unicidade-manual.sql no MySQL; no PostgreSQL aplicar
-- ADD CONSTRAINT equivalente após a mesma auditoria. NÃO apagar/consolidar dados.

ALTER TABLE estoque ADD COLUMN estoque_minimo DOUBLE PRECISION NULL;
ALTER TABLE estoque ADD COLUMN estoque_maximo DOUBLE PRECISION NULL;
ALTER TABLE estoque ADD CONSTRAINT ck_estoque_minimo CHECK (estoque_minimo IS NULL OR estoque_minimo >= 0);
ALTER TABLE estoque ADD CONSTRAINT ck_estoque_maximo CHECK (estoque_maximo IS NULL OR estoque_maximo >= 0);
ALTER TABLE estoque ADD CONSTRAINT ck_estoque_limites CHECK (estoque_minimo IS NULL OR estoque_maximo IS NULL OR estoque_maximo >= estoque_minimo);

CREATE TABLE transferencia_estoque (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    almoxarifado_origem_id INT NOT NULL,
    almoxarifado_destino_id INT NOT NULL,
    responsavel_id INT NOT NULL,
    data_hora TIMESTAMP(6) NOT NULL,
    status VARCHAR(30) NOT NULL,
    observacao VARCHAR(1000) NULL,
    CONSTRAINT fk_transferencia_origem FOREIGN KEY (almoxarifado_origem_id) REFERENCES almoxarifado(id),
    CONSTRAINT fk_transferencia_destino FOREIGN KEY (almoxarifado_destino_id) REFERENCES almoxarifado(id),
    CONSTRAINT fk_transferencia_responsavel FOREIGN KEY (responsavel_id) REFERENCES funcionario(id),
    CONSTRAINT ck_transferencia_locais CHECK (almoxarifado_origem_id <> almoxarifado_destino_id),
    CONSTRAINT ck_transferencia_status CHECK (status = 'CONCLUIDA')
);
CREATE TABLE item_transferencia (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferencia_id INT NOT NULL,
    produto_id INT NOT NULL,
    quantidade DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_item_transferencia FOREIGN KEY (transferencia_id) REFERENCES transferencia_estoque(id),
    CONSTRAINT fk_item_transferencia_produto FOREIGN KEY (produto_id) REFERENCES produto(id),
    CONSTRAINT uk_item_transferencia_produto UNIQUE (transferencia_id, produto_id),
    CONSTRAINT ck_item_transferencia_quantidade CHECK (quantidade > 0)
);
ALTER TABLE movimentacao ADD COLUMN transferencia_id INT NULL;
ALTER TABLE movimentacao ADD CONSTRAINT fk_movimentacao_transferencia
    FOREIGN KEY (transferencia_id) REFERENCES transferencia_estoque(id);
CREATE INDEX idx_transferencia_origem_data ON transferencia_estoque(almoxarifado_origem_id, data_hora);
CREATE INDEX idx_transferencia_destino_data ON transferencia_estoque(almoxarifado_destino_id, data_hora);
CREATE INDEX idx_transferencia_responsavel ON transferencia_estoque(responsavel_id);
CREATE INDEX idx_item_transferencia_produto ON item_transferencia(produto_id, transferencia_id);
CREATE INDEX idx_movimentacao_transferencia ON movimentacao(transferencia_id, id);
-- FKs não possuem cascata de exclusão. Legados ficam com limites/vínculo NULL.
-- Finitude das quantidades continua validada no service Java.
-- PostgreSQL admite NaN/Infinity em DOUBLE PRECISION: checks adicionais explícitos.
ALTER TABLE estoque ADD CONSTRAINT ck_estoque_limites_finitos CHECK (
 (estoque_minimo IS NULL OR estoque_minimo BETWEEN 0 AND '1.7976931348623157e308'::DOUBLE PRECISION) AND
 (estoque_maximo IS NULL OR estoque_maximo BETWEEN 0 AND '1.7976931348623157e308'::DOUBLE PRECISION));
ALTER TABLE item_transferencia ADD CONSTRAINT ck_item_transferencia_finito CHECK (
 quantidade <= '1.7976931348623157e308'::DOUBLE PRECISION);
