-- SECURITY BASELINE 2: manual preparation only, NOT executed.
-- Review backup/schema and funcionario.id type first. No operational data changes.
-- No initial user, hash, password or credentials. Bootstrap externally afterward.
-- Roles/permissions are Java enums; profile column stores their approved names.
-- PostgreSQL future deployment requires its JDBC driver/config/integration validation.
BEGIN;
CREATE TABLE bes_usuario (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username VARCHAR(80) NOT NULL,
 senha_hash VARCHAR(100) NOT NULL,
 bootstrap_chave VARCHAR(20) NULL,
 nome_exibicao VARCHAR(120) NOT NULL,
 perfil VARCHAR(20) NOT NULL,
 ativo BOOLEAN NOT NULL,
 funcionario_id INTEGER NULL,
 criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 ultimo_login_em TIMESTAMP(6) WITH TIME ZONE NULL,
 auth_version BIGINT NOT NULL,
 versao BIGINT NOT NULL,
 CONSTRAINT uk_bes_usuario_username UNIQUE (username),
 CONSTRAINT uk_bes_usuario_bootstrap UNIQUE (bootstrap_chave),
 CONSTRAINT fk_bes_usuario_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionario(id),
 CONSTRAINT ck_bes_usuario_perfil CHECK (perfil IN ('ADMIN','GESTOR','ALMOXARIFE','CONSULTA'))
);
CREATE TABLE bes_auditoria (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 instante TIMESTAMP(6) WITH TIME ZONE NOT NULL,
 ator_id BIGINT NULL,
 ator_username VARCHAR(80) NULL,
 evento VARCHAR(100) NOT NULL,
 entidade VARCHAR(100) NULL,
 referencia VARCHAR(80) NULL,
 resultado VARCHAR(20) NOT NULL,
 responsavel_operacional_id INTEGER NULL,
 request_id VARCHAR(36) NULL,
 antes VARCHAR(1500) NULL,
 depois VARCHAR(1500) NULL
);
CREATE INDEX ix_bes_auditoria_instante ON bes_auditoria(instante);
CREATE INDEX ix_bes_auditoria_ator ON bes_auditoria(ator_id);
CREATE INDEX ix_bes_usuario_funcionario ON bes_usuario(funcionario_id);
COMMIT;
-- Actor/responsible ids are historical snapshots; never cascade/delete history.
-- Review runtime grants externally, especially audit INSERT/SELECT only.
