package br.com.almoxarifado.ativos;
import br.com.almoxarifado.compras.ComprasPage;
import java.util.Map;
import java.time.LocalDate;
import org.springframework.web.bind.annotation.*;
@RestController
public class AtivosController {
 private final AtivosService service;
 public AtivosController(AtivosService s){service=s;}
 @GetMapping("/ativos") public ComprasPage<Map<String,Object>> listar(@RequestParam(required=false) String termo,@RequestParam(required=false) StatusAtivo status,@RequestParam(required=false) CondicaoAtivo condicao,@RequestParam(required=false) Integer categoriaId,@RequestParam(required=false) Integer funcionarioId,@RequestParam(required=false) Integer almoxarifadoId,@RequestParam(required=false) Integer obraId,@RequestParam(required=false) Integer ordemServicoId,@RequestParam(required=false) Integer centroCustoId,@RequestParam(required=false) Boolean ativo,@RequestParam(required=false) Boolean inspecaoPendente,@RequestParam(defaultValue="0") int pagina,@RequestParam(defaultValue="20") int tamanho){return ComprasPage.of(service.listar(new AtivosService.Filtro(termo,status,condicao,categoriaId,funcionarioId,almoxarifadoId,obraId,ordemServicoId,centroCustoId,ativo,inspecaoPendente),pagina,tamanho));}
 @GetMapping("/ativos/resumo") public Map<String,Object> resumo(){return service.resumo();}
 @GetMapping("/ativos/{id}") public Map<String,Object> buscar(@PathVariable Integer id){return service.buscar(id);}
 @GetMapping("/ativos/{id}/historico") public ComprasPage<Map<String,Object>> historico(@PathVariable Integer id,@RequestParam(defaultValue="0") int pagina,@RequestParam(defaultValue="20") int tamanho){return ComprasPage.of(service.historico(id,pagina,tamanho));}
 @PostMapping("/ativos") public Map<String,Object> criar(@RequestBody AtivosInput.Criacao in){return service.criar(in);}
 @PutMapping("/ativos/{id}") public Map<String,Object> editar(@PathVariable Integer id,@RequestBody AtivosInput.Cadastro in){return service.editar(id,in);}
 @PutMapping("/ativos/{id}/situacao") public Map<String,Object> situacao(@PathVariable Integer id,@RequestBody AtivosInput.Situacao in,@RequestHeader("Idempotency-Key") String chave){return service.situacao(id,in,chave);}
 @GetMapping("/emprestimos") public ComprasPage<Map<String,Object>> listarEmprestimo(@RequestParam(required=false) Integer ativoId,@RequestParam(required=false) Integer funcionarioId,@RequestParam(required=false) Integer obraId,@RequestParam(required=false) Integer ordemServicoId,@RequestParam(required=false) Integer centroCustoId,@RequestParam(required=false) Boolean aberto,@RequestParam(required=false) Boolean vencido,@RequestParam(required=false) LocalDate de,@RequestParam(required=false) LocalDate ate,@RequestParam(defaultValue="0") int pagina,@RequestParam(defaultValue="20") int tamanho){return ComprasPage.of(service.listarRegistros(TipoRegistroAtivo.EMPRESTIMO,ativoId,funcionarioId,obraId,ordemServicoId,centroCustoId,aberto,vencido,de,ate,pagina,tamanho));}
 @GetMapping("/emprestimos/{id}") public Map<String,Object> buscarEmprestimo(@PathVariable Integer id){return service.buscarRegistro(id,TipoRegistroAtivo.EMPRESTIMO);}
 @PostMapping("/emprestimos") public Map<String,Object> emprestar(@RequestBody AtivosInput.Emprestimo in,@RequestHeader("Idempotency-Key") String chave){return service.emprestar(in,chave);}
 @GetMapping("/transferencias-ativos") public ComprasPage<Map<String,Object>> listarTransferencia(@RequestParam(required=false) Integer ativoId,@RequestParam(required=false) Integer funcionarioId,@RequestParam(required=false) Integer obraId,@RequestParam(required=false) Integer ordemServicoId,@RequestParam(required=false) Integer centroCustoId,@RequestParam(required=false) Boolean aberto,@RequestParam(required=false) Boolean vencido,@RequestParam(required=false) LocalDate de,@RequestParam(required=false) LocalDate ate,@RequestParam(defaultValue="0") int pagina,@RequestParam(defaultValue="20") int tamanho){return ComprasPage.of(service.listarRegistros(TipoRegistroAtivo.TRANSFERENCIA,ativoId,funcionarioId,obraId,ordemServicoId,centroCustoId,aberto,vencido,de,ate,pagina,tamanho));}
 @GetMapping("/transferencias-ativos/{id}") public Map<String,Object> buscarTransferencia(@PathVariable Integer id){return service.buscarRegistro(id,TipoRegistroAtivo.TRANSFERENCIA);}
 @PostMapping("/transferencias-ativos") public Map<String,Object> transferir(@RequestBody AtivosInput.Transferencia in,@RequestHeader("Idempotency-Key") String chave){return service.transferir(in,chave);}
 @GetMapping("/inspecoes-ativos") public ComprasPage<Map<String,Object>> listarInspecao(@RequestParam(required=false) Integer ativoId,@RequestParam(required=false) Integer funcionarioId,@RequestParam(required=false) Integer obraId,@RequestParam(required=false) Integer ordemServicoId,@RequestParam(required=false) Integer centroCustoId,@RequestParam(required=false) Boolean aberto,@RequestParam(required=false) Boolean vencido,@RequestParam(required=false) LocalDate de,@RequestParam(required=false) LocalDate ate,@RequestParam(defaultValue="0") int pagina,@RequestParam(defaultValue="20") int tamanho){return ComprasPage.of(service.listarRegistros(TipoRegistroAtivo.INSPECAO,ativoId,funcionarioId,obraId,ordemServicoId,centroCustoId,aberto,vencido,de,ate,pagina,tamanho));}
 @GetMapping("/inspecoes-ativos/{id}") public Map<String,Object> buscarInspecao(@PathVariable Integer id){return service.buscarRegistro(id,TipoRegistroAtivo.INSPECAO);}
 @PostMapping("/inspecoes-ativos") public Map<String,Object> inspecionar(@RequestBody AtivosInput.Inspecao in,@RequestHeader("Idempotency-Key") String chave){return service.inspecionar(in,chave);}
 @PostMapping("/emprestimos/{id}/devolucao") public Map<String,Object> devolver(@PathVariable Integer id,@RequestBody AtivosInput.Devolucao in,@RequestHeader("Idempotency-Key") String chave){return service.devolver(id,in,chave);}
 @PostMapping("/transferencias-ativos/{id}/recebimento") public Map<String,Object> receber(@PathVariable Integer id,@RequestBody AtivosInput.Recebimento in,@RequestHeader("Idempotency-Key") String chave){return service.receber(id,in,chave);}
}
