package br.com.almoxarifado.security;
public enum Permissao {
 EPI_LER, EPI_GERENCIAR, EPI_ENTREGA_LER, EPI_ENTREGA_GERENCIAR,
 ATIVO_LER, ATIVO_GERENCIAR, EMPRESTIMO_LER, EMPRESTIMO_GERENCIAR, TRANSFERENCIA_ATIVO_LER, TRANSFERENCIA_ATIVO_GERENCIAR, INSPECAO_ATIVO_LER, INSPECAO_ATIVO_GERENCIAR,
 OBRA_LER, OBRA_GERENCIAR, ORDEM_SERVICO_LER, ORDEM_SERVICO_GERENCIAR, CENTRO_CUSTO_LER, CENTRO_CUSTO_GERENCIAR,
 FORNECEDOR_LER, FORNECEDOR_GERENCIAR, COMPRA_LER, COMPRA_CRIAR, COMPRA_APROVAR, COMPRA_CANCELAR, RECEBIMENTO_LER, RECEBIMENTO_REGISTRAR, NECESSIDADE_COMPRA_GERENCIAR,
 USUARIO_GERENCIAR, AUDITORIA_LER,
 PRODUTO_LER, PRODUTO_GERENCIAR, CATEGORIA_LER, CATEGORIA_GERENCIAR, UNIDADE_LER, UNIDADE_GERENCIAR,
 ESTOQUE_LER, ESTOQUE_MOVIMENTAR, ESTOQUE_TRANSFERIR, ESTOQUE_CONFIGURAR,
 SOLICITACAO_LER, SOLICITACAO_CRIAR, SOLICITACAO_APROVAR, SOLICITACAO_REJEITAR, SOLICITACAO_SEPARAR, SOLICITACAO_ATENDER,
 NECESSIDADE_COMPRA_LER, NECESSIDADE_COMPRA_CRIAR, MOVIMENTACAO_LER,
 FUNCIONARIO_LER, FUNCIONARIO_GERENCIAR, ALMOXARIFADO_LER, ALMOXARIFADO_GERENCIAR
}
