import { test, expect } from './security-support.js'
const base='http://localhost:8081'
async function call(request,path,method='GET',data){const r=await request.fetch(base+path,{method,...(data?{data,headers:{'Idempotency-Key':crypto.randomUUID()}}:{})});expect(r.ok(),`${path} ${r.status()}`).toBeTruthy();return r.json()}
async function setup(request){const stamp=Date.now()+'-'+Math.random().toString(36).slice(2,6);const person=await call(request,'/funcionarios','POST',{nome:'Operador QA '+stamp,matricula:'QA-'+stamp});const warehouse=await call(request,'/almoxarifados','POST',{nome:'Central QA '+stamp});const create=()=>call(request,'/ativos','POST',{cadastro:{nome:'Furadeira Bosch '+stamp,fabricante:'Bosch',modelo:'GBH 2-26',numeroSerie:'QA-'+stamp},almoxarifadoId:warehouse.id,condicao:'BOM'});const asset=await create();return {stamp,person,warehouse,asset,create}}
async function structure(request,stamp){const obra=await call(request,'/obras','POST',{codigo:'QA-OB-'+stamp,nome:'Obra QA '+stamp});const cc=await call(request,'/centros-custo','POST',{codigo:'QA-CC-'+stamp,nome:'Montagem '+stamp,tipo:'OBRA',ativo:true,obraId:obra.id});const os=await call(request,'/ordens-servico','POST',{obraId:obra.id,centroCustoId:cc.id,titulo:'Serviço QA '+stamp});return {obra,cc,os,contexto:{obraId:obra.id,ordemServicoId:os.id,centroCustoId:cc.id}}}
const loan=(f,asset=f.asset,contexto)=>({ativoId:asset.id,entreguePorId:f.person.id,funcionarioId:f.person.id,condicao:'BOM',contexto})
async function close(page){await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).last().click();await expect(page.getByRole('dialog')).not.toBeVisible()}
async function shot(page,name,width){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`test-results/b6-audit-${name}-${width}.png`,fullPage:true})}
test('B6 auditoria comprovantes mantêm origem após renomear e mudar localização',async({page,request})=>{
 const f=await setup(request),a=await structure(request,f.stamp+'A'),b=await structure(request,f.stamp+'B');const original=await call(request,'/emprestimos','POST',{...loan(f,f.asset,a.contexto),observacao:'Marca preexistente\nCondição conferida sem atribuir culpa'});expect((await call(request,'/ativos/'+f.asset.id)).almoxarifadoId).toBeNull();await call(request,`/emprestimos/${original.id}/devolucao`,'POST',{devolvidoPorId:f.person.id,recebidoPorId:f.person.id,condicao:'REGULAR',observacao:'Devolução registrada\nSem nova avaria'});const sent=await call(request,'/transferencias-ativos','POST',{ativoId:f.asset.id,entreguePorId:f.person.id,contexto:b.contexto,condicao:'REGULAR'});await call(request,`/transferencias-ativos/${sent.id}/recebimento`,'POST',{recebidoPorId:f.person.id,condicao:'REGULAR'});await call(request,'/obras/'+a.obra.id,'PUT',{codigo:a.obra.codigo,nome:'Nome cosmético alterado'});await call(request,'/ativos/'+f.asset.id,'PUT',{codigoPatrimonial:f.asset.codigoPatrimonial,nome:'Ativo renomeado'});await call(request,'/funcionarios/'+f.person.id,'PUT',{nome:'Funcionário renomeado',matricula:f.person.matricula});
 await page.goto(`/emprestimos/${original.id}/documento`);const doc=page.locator('.operational-document');await expect(doc).toContainText(a.obra.nome);await expect(doc).toContainText(a.os.numero);await expect(doc).toContainText(a.cc.codigo);await expect(doc).toContainText(f.asset.nome);await expect(doc).toContainText(f.person.nome);await expect(doc).not.toContainText(b.obra.nome);await expect(doc).not.toContainText('Ativo renomeado');await expect(doc).not.toContainText('Funcionário renomeado');await expect(doc).toContainText('Devolução confirmada');await page.emulateMedia({media:'print'});await expect(page.locator('.document-actions')).toBeHidden();await page.pdf({path:'test-results/b6-audit-comprovante-historico.pdf',format:'A4'});await page.emulateMedia({media:'screen'});await page.goto(`/transferencias-ativos/${sent.id}/documento`);await expect(doc).toContainText(b.obra.nome);await expect(doc).toContainText('Chegada confirmada');await page.emulateMedia({media:'print'});await page.pdf({path:'test-results/b6-audit-transferencia-historica.pdf',format:'A4'});
})
test('B6 auditoria duplo clique produz um request e feedback de sucesso',async({page,request})=>{const f=await setup(request);await page.goto('/ativos/'+f.asset.id);await page.getByRole('button',{name:'Registrar empréstimo',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByLabel('Obra',{exact:true})).toBeHidden();await d.getByLabel('Quem entregou',{exact:true}).selectOption(String(f.person.id));await d.getByLabel('Funcionário que recebeu',{exact:true}).selectOption(String(f.person.id));await d.getByLabel('Observações / divergência',{exact:true}).fill('Conferido\nSem avaria');let writes=0;await page.route('**/api/emprestimos',async route=>{if(route.request().method()==='POST'){writes++;await new Promise(r=>setTimeout(r,300))}await route.continue()});await d.getByRole('button',{name:'Confirmar operação',exact:true}).click({clickCount:2});await expect(d).not.toBeVisible();expect(writes).toBe(1);await expect(page.getByText('Operação confirmada. Estado e histórico atualizados.',{exact:true})).toBeVisible();expect((await call(request,'/ativos/'+f.asset.id+'/historico')).totalElements).toBe(1)})
test('B6 auditoria reprovação também bloqueia chamada direta do cliente',async({page,request})=>{const f=await setup(request);await call(request,'/inspecoes-ativos','POST',{ativoId:f.asset.id,inspetorId:f.person.id,condicao:'DANIFICADO',resultado:'REPROVADO',observacao:'Avaria constatada'});await page.goto('/ativos/'+f.asset.id);await expect(page.getByText('Inspeção reprovada. Novo empréstimo bloqueado até aprovação.',{exact:true})).toBeVisible();const r=await request.post(base+'/emprestimos',{headers:{'Idempotency-Key':crypto.randomUUID()},data:loan(f)});expect(r.status()).toBe(409);expect((await call(request,'/ativos/'+f.asset.id+'/historico')).totalElements).toBe(1)})
test('B6 auditoria lista vazia, 403 e falha de rede mantêm feedback acessível',async({page})=>{await page.route('**/api/ativos?*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({content:[],number:0,size:20,totalElements:0,totalPages:0,first:true,last:true})}));await page.goto('/ativos');await expect(page.getByText('Nenhum registro encontrado.',{exact:true})).toBeVisible();await page.unroute('**/api/ativos?*');await page.route('**/api/ativos?*',route=>route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({mensagem:'Operação não autorizada'})}));await page.reload();await expect(page.getByRole('alert').filter({hasText:'Operação não autorizada'})).toBeVisible();await page.unroute('**/api/ativos?*');await page.route('**/api/ativos?*',route=>route.abort('failed'));await page.reload();await expect(page.getByRole('button',{name:'Tentar novamente',exact:true})).toBeVisible()})
for(const width of [1440,768,390])test('B6 auditoria visual de listas, detalhes, cinco operações e documentos '+width,async({page,request})=>{
 const f=await setup(request),ctx=await structure(request,f.stamp),borrowed=await f.create(),transit=await f.create();const l=await call(request,'/emprestimos','POST',loan(f,borrowed));const t=await call(request,'/transferencias-ativos','POST',{ativoId:transit.id,entreguePorId:f.person.id,contexto:ctx.contexto,condicao:'BOM'});await page.setViewportSize({width,height:900});
 for(const [name,path] of [['lista','/ativos'],['emprestimos','/emprestimos'],['transferencias','/transferencias-ativos'],['inspecoes','/inspecoes-ativos'],['detalhe','/ativos/'+f.asset.id]]){await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByRole('status').filter({hasText:'Carregando informações'})).toHaveCount(0);await shot(page,name,width)}
 for(const [name,asset,button] of [['emprestar',f.asset,'Registrar empréstimo'],['devolver',borrowed,'Devolver ativo'],['transferir',f.asset,'Enviar transferência'],['chegada',transit,'Confirmar chegada'],['inspecionar',f.asset,'Registrar inspeção']]){await page.goto('/ativos/'+asset.id);await page.getByRole('button',{name:button,exact:true}).click();const d=page.getByRole('dialog');await expect(d).toContainText(asset.codigoPatrimonial);if(name==='chegada')await expect(d).toContainText(ctx.obra.nome);if(name==='devolver')await expect(d.getByLabel('Quem devolveu',{exact:true})).toHaveValue(String(f.person.id));const bounds=await d.boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(width);await shot(page,name,width);await d.getByRole('button',{name:'Confirmar operação',exact:true}).focus();await expect(d.getByRole('button',{name:'Confirmar operação',exact:true})).toBeFocused();await expect(d.getByRole('button',{name:'Confirmar opera\u00e7\u00e3o',exact:true})).toBeInViewport();await close(page)}
 for(const [name,path] of [['ficha',`/ativos/${borrowed.id}/ficha`],['comprovante',`/emprestimos/${l.id}/documento`],['envio',`/transferencias-ativos/${t.id}/documento`]]){await page.goto(path);await expect(page.locator('.operational-document')).toBeVisible();if(name==='ficha'){await expect(page.locator('.operational-document')).toContainText(f.person.nome);await expect(page.locator('.operational-document')).toContainText(f.warehouse.nome)}await shot(page,name,width);await page.emulateMedia({media:'print'});await expect(page.locator('.document-actions')).toBeHidden();expect(await page.locator('.sidebar').count()).toBe(0);await page.pdf({path:`test-results/b6-audit-${name}-${width}.pdf`,format:'A4'});await page.emulateMedia({media:'screen'})}
})

test('B6 auditoria pesquisa conserva ativo selecionado fora do resultado',async({page,request})=>{const f=await setup(request),other=await f.create();await page.goto('/emprestimos');await page.getByRole('button',{name:'Registrar empréstimo',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('Ativo',{exact:true}).selectOption(String(f.asset.id));await d.getByLabel('Pesquisar ativo para selecionar',{exact:true}).fill(other.codigoPatrimonial);await expect(d.getByLabel('Ativo',{exact:true})).toHaveValue(String(f.asset.id));await expect(d.getByLabel('Ativo',{exact:true}).locator('option:checked')).toContainText(f.asset.codigoPatrimonial);await close(page)})
