import {test,expect,fixtures} from './security-support.js'
const base='http://localhost:8081'
test('B7 teclado mantém foco no modal e Escape retorna à ação',async({page})=>{
 await page.goto('/epis');
 const open=page.getByRole('button',{name:'Configurar EPI',exact:true});
 await open.focus();await page.keyboard.press('Enter');
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();
 await expect(dialog.getByLabel('CA',{exact:true})).toBeVisible();
 for(let i=0;i<20;i++){
  await page.keyboard.press('Tab');
  expect(await dialog.evaluate(d=>d.contains(document.activeElement))).toBeTruthy();
 }
 await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(open).toBeFocused();
})
async function call(request,path,method='GET',data){const r=await request.fetch(base+path,{method,...(data?{data,headers:{'Idempotency-Key':crypto.randomUUID()}}:{})});expect(r.ok(),path+' '+r.status()).toBeTruthy();return r.json()}
async function setup(request){const stamp=Date.now()+'-'+Math.random().toString(36).slice(2,6),person=await call(request,'/funcionarios','POST',{nome:'Recebedor EPI '+stamp,matricula:'EP-'+stamp}),warehouse=await call(request,'/almoxarifados','POST',{nome:'Central EPI '+stamp}),products=[];for(const name of ['Capacete','Óculos']){const p=await call(request,'/produtos','POST',{nome:name+' '+stamp,codigo:'EP-'+products.length+'-'+stamp,unidadeMedida:'UN'});await call(request,'/estoques','POST',{produto:{id:p.id},almoxarifado:{id:warehouse.id},quantidade:0});await call(request,`/estoques/entrada?produtoId=${p.id}&almoxarifadoId=${warehouse.id}&quantidade=5&solicitanteId=${person.id}&responsavelId=${person.id}`,'PUT');await call(request,'/epis','POST',{produtoId:p.id,ca:'12345',modelo:'Modelo H2',tamanho:'M',ativo:true,exigeDevolucao:true,permiteRetorno:true});products.push(p)}return {stamp,person,warehouse,products}}
function body(f){return {funcionarioId:f.person.id,responsavelId:f.person.id,almoxarifadoId:f.warehouse.id,motivo:'INICIAL',recebimentoConfirmado:true,itens:f.products.map(p=>({produtoId:p.id,quantidade:'1'}))}}
test('B7 duplo clique gera uma confirmação física',async({page,request})=>{const f=await setup(request);await fill(page,f);let writes=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/epi-entregas'))writes++});await page.getByRole('button',{name:'Confirmar entrega',exact:true}).evaluate(b=>{b.click();b.click()});await expect(page).toHaveURL(/epi-entregas\/\d+$/);expect(writes).toBe(1);expect(await stock(request,f)).toBe(4)})
test('B7 substituição UI liga origem com condição e destino explícitos',async({page,request})=>{const f=await setup(request);const original=await call(request,'/epi-entregas','POST',body(f));await fill(page,f);await page.getByLabel('Tipo da entrega',{exact:true}).selectOption('SUBSTITUICAO');for(let j=0;j<2;j++){await page.getByLabel(`Entrega anterior do item ${j+1}`,{exact:true}).selectOption(String(original.itens[j].id));await page.getByLabel(`Condição anterior do item ${j+1}`,{exact:true}).selectOption('USADO');await page.getByLabel(`Destino anterior do item ${j+1}`,{exact:true}).selectOption('SEGREGADO');await page.getByLabel(`Motivo da substituição do item ${j+1}`,{exact:true}).fill('Desgaste conferido')}await page.getByRole('button',{name:'Confirmar entrega',exact:true}).click();await expect(page).toHaveURL(/epi-entregas\/\d+$/);expect(await stock(request,f)).toBe(3);const history=await call(request,'/epi-entregas?funcionarioId='+f.person.id);expect(history.content[0].tipo).toBe('SUBSTITUICAO');expect(history.content[0].itens.filter(i=>!i.entrega).every(i=>i.destino==='SEGREGADO'&&i.condicao==='USADO')).toBeTruthy()})
test('B7 documento conserva CA e nome após alteração do catálogo',async({page,request})=>{const f=await setup(request),b=body(f);b.itens=b.itens.slice(0,1);b.itens[0].quantidade='5';const r=await call(request,'/epi-entregas','POST',b);const p=f.products[0];const rename=await request.put(base+'/produtos/'+p.id,{data:{...p,nome:'Nome novo H2'}});expect(rename.ok()).toBeTruthy();await call(request,'/epis/'+p.id,'PUT',{produtoId:p.id,ca:'67890',modelo:'Outro modelo',ativo:true,exigeDevolucao:true,permiteRetorno:true});await page.goto(`/epi-entregas/${r.id}/documento`);await expect(page.locator('.operational-document')).toContainText(p.nome);await expect(page.locator('.operational-document')).toContainText('12345');await expect(page.locator('.operational-document')).not.toContainText('67890');await expect(page.locator('.operational-document')).not.toContainText('Nome novo H2')})
test('B7 lista vazia, carregamento, erro e recuperação acessíveis',async({page})=>{let release;const gate=new Promise(resolve=>release=resolve);async function capture(state){for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});await page.screenshot({path:`test-results/b7-${state}-${width}.png`,fullPage:true})}}await page.route('**/api/epis?*',async route=>{await gate;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({content:[],totalElements:0,totalPages:0,number:0,first:true,last:true})})},{times:1});await page.goto('/epis');await expect(page.getByRole('status')).toContainText('Carregando');await capture('loading');release();await expect(page.getByText('Nenhum registro encontrado.',{exact:true})).toBeVisible();await capture('empty');await page.route('**/api/epis?*',route=>route.abort('failed'),{times:1});await page.getByLabel('Pesquisar EPIs',{exact:true}).fill('Sem rede H2');await expect(page.getByRole('alert')).toContainText('Não foi possível carregar');await capture('error');await page.getByRole('button',{name:'Tentar novamente',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0)})
async function stock(request,f,p=f.products[0]){return (await call(request,`/estoques/produto/${p.id}/almoxarifado/${f.warehouse.id}`)).quantidade}
async function fill(page,f){await page.goto('/epi-entregas/nova');await page.getByLabel('Funcionário que recebe',{exact:true}).selectOption(String(f.person.id));await page.getByLabel('Responsável pela entrega',{exact:true}).selectOption(String(f.person.id));await page.getByLabel('Almoxarifado de origem',{exact:true}).selectOption(String(f.warehouse.id));for(const p of f.products){await page.getByLabel('Pesquisar EPI para adicionar',{exact:true}).fill(p.codigo);await expect(page.getByLabel('EPI disponível',{exact:true}).locator('option')).toHaveCount(2);await page.getByLabel('EPI disponível',{exact:true}).selectOption(String(p.id));await page.getByRole('button',{name:'Adicionar EPI',exact:true}).click()}await page.getByRole('checkbox').check()}
async function closeForm(page,f,dest='SEGREGADO'){const d=page.getByRole('dialog');await d.getByLabel('Responsável pelo encerramento',{exact:true}).selectOption(String(f.person.id));await d.getByLabel('Almoxarifado que recebe / registra',{exact:true}).selectOption(String(f.warehouse.id));await d.getByLabel('Condição constatada',{exact:true}).selectOption('NOVO');await d.getByLabel('Destino do EPI',{exact:true}).selectOption(dest);await d.getByLabel('Motivo / observação',{exact:true}).fill('Conferência física H2');await d.getByRole('button',{name:'Confirmar encerramento',exact:true}).click();await expect(d).not.toBeVisible()}
test('B7 entrega múltipla pela UI, ficha, documento e devolução segregada',async({page,request})=>{const f=await setup(request);await fill(page,f);await page.getByLabel('Quantidade do item 1',{exact:true}).fill('2');await page.getByRole('button',{name:'Confirmar entrega',exact:true}).click();await expect(page).toHaveURL(/epi-entregas\/\d+$/);expect(await stock(request,f)).toBe(3);expect(await stock(request,f,f.products[1])).toBe(4);await page.getByRole('link',{name:'Comprovante do registro',exact:true}).click();await expect(page.locator('.operational-document')).toContainText(f.person.nome);await expect(page.locator('.operational-document')).toContainText('12345');await page.goto('/epi-funcionarios/'+f.person.id);await page.getByRole('button',{name:/Devolver item/}).first().click();await closeForm(page,f);expect(await stock(request,f)).toBe(3);expect(await stock(request,f,f.products[1])).toBe(4);await expect(page.getByRole('table').last()).toContainText('Devolução')})
test('B7 saldo insuficiente bloqueia lote inteiro e UI',async({page,request})=>{const f=await setup(request);const b=body(f);b.itens[1].quantidade='6';const r=await request.post(base+'/epi-entregas',{data:b,headers:{'Idempotency-Key':crypto.randomUUID()}});expect(r.status()).toBe(409);for(const p of f.products)expect(await stock(request,f,p)).toBe(5);expect((await call(request,'/epi-entregas?funcionarioId='+f.person.id)).totalElements).toBe(0);await fill(page,f);await page.getByLabel('Quantidade do item 2',{exact:true}).fill('6');await page.getByRole('button',{name:'Confirmar entrega',exact:true}).click();await expect(page.getByText('Saldo insuficiente para '+f.products[1].nome+'.',{exact:true})).toBeVisible();expect((await call(request,'/epi-entregas?funcionarioId='+f.person.id)).totalElements).toBe(0)})
test('B7 resposta perdida reenvia chave e corpo sem segunda saída',async({page,request})=>{const f=await setup(request);await fill(page,f);let key,payload;await page.route('**/api/epi-entregas',async route=>{key=route.request().headers()['idempotency-key'];payload=route.request().postData();await route.fetch();await route.abort('failed')},{times:1});await page.getByRole('button',{name:'Confirmar entrega',exact:true}).click();await expect(page.getByRole('button',{name:'Reenviar mesma confirmação',exact:true})).toBeVisible();await page.route('**/api/epi-entregas',async route=>{expect(route.request().headers()['idempotency-key']).toBe(key);expect(route.request().postData()).toBe(payload);await route.continue()},{times:1});await page.getByRole('button',{name:'Reenviar mesma confirmação',exact:true}).click();await expect(page).toHaveURL(/epi-entregas\/\d+$/);expect(await stock(request,f)).toBe(4);expect((await call(request,'/epi-entregas?funcionarioId='+f.person.id)).totalElements).toBe(1)})
test('B7 retorno NOVO explícito credita, descarte não credita',async({page,request})=>{const f=await setup(request);await call(request,'/epi-entregas','POST',body(f));await page.goto('/epi-funcionarios/'+f.person.id);await page.getByRole('button',{name:/Devolver item/}).first().click();await closeForm(page,f,'ESTOQUE');expect((await stock(request,f))+(await stock(request,f,f.products[1]))).toBe(9);const item=(await call(request,'/epi-entregas/posse?funcionarioId='+f.person.id)).content[0];await call(request,'/epi-descartes','POST',{responsavelId:f.person.id,almoxarifadoId:f.warehouse.id,motivo:'Dano constatado',itens:[{origemItemId:item.id,quantidade:'1',condicao:'DANIFICADO',destino:'DESCARTE'}]});expect((await stock(request,f))+(await stock(request,f,f.products[1]))).toBe(9);expect((await call(request,'/epi-entregas/posse?funcionarioId='+f.person.id)).totalElements).toBe(0)})
test('B7 contexto coerente e incompatível rejeitado',async({request})=>{const f=await setup(request),obra=await call(request,'/obras','POST',{codigo:'EP-OB-'+f.stamp,nome:'Obra EPI'}),cc=await call(request,'/centros-custo','POST',{codigo:'EP-CC-'+f.stamp,nome:'Centro EPI',tipo:'OBRA',ativo:true,obraId:obra.id}),os=await call(request,'/ordens-servico','POST',{titulo:'Montagem EPI',obraId:obra.id,centroCustoId:cc.id}),b=body(f);b.contexto={obraId:obra.id,centroCustoId:cc.id,ordemServicoId:os.id};const r=await call(request,'/epi-entregas','POST',b);expect(r.contexto.obraId).toBe(obra.id);expect(r.itens[0].contexto.ordemServicoId).toBe(os.id);const outra=await call(request,'/obras','POST',{codigo:'EP-OT-'+f.stamp,nome:'Outra obra'});b.contexto.obraId=outra.id;const bad=await request.post(base+'/epi-entregas',{data:b,headers:{'Idempotency-Key':crypto.randomUUID()}});expect(bad.status()).toBe(409);expect(await stock(request,f)).toBe(4)})
for(const profile of ['ALMOXARIFE','CONSULTA'])test('B7 permissões visuais '+profile,async({page,request})=>{const f=await setup(request);await page.context().clearCookies();await page.goto('/login');await page.getByLabel('Usuário',{exact:true}).fill(fixtures[profile].username);await page.getByLabel('Senha',{exact:true}).fill(fixtures[profile].password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/dashboard$/);await page.goto('/epis');await expect(page.getByRole('heading',{level:1})).toHaveText('EPIs');await expect(page.getByRole('button',{name:'Configurar EPI',exact:true})).toHaveCount(0);await page.goto('/epi-entregas');await expect(page.getByRole('link',{name:'Nova entrega',exact:true})).toHaveCount(profile==='ALMOXARIFE'?1:0)})
for(const width of [1440,768,390])test('B7 revisão visual telas e A4 '+width,async({page,request})=>{const f=await setup(request);await page.setViewportSize({width,height:900});for(const path of ['/epis','/epi-entregas']){await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByRole('table')).toBeVisible();await expect(page.getByRole('status').filter({hasText:'Carregando informa??es'})).toHaveCount(0);if(path==='/epis'){const ca=page.locator('.epi-config-list tbody tr').first().locator('td').nth(1).locator('strong');await expect(ca).toHaveText('12345');expect((await ca.boundingBox()).height).toBeLessThan(24)}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/b7-${path.slice(1)}-${width}.png`,fullPage:true})}await fill(page,f);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/b7-entrega-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Confirmar entrega',exact:true}).click();await expect(page).toHaveURL(/epi-entregas\/\d+$/);const id=page.url().split('/').pop();await page.goto('/epi-funcionarios/'+f.person.id);await expect(page.getByRole('button',{name:/Devolver item/}).first()).toBeVisible();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/b7-ficha-${width}.png`,fullPage:true});await page.getByRole('button',{name:/Devolver item/}).first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/b7-modal-${width}.png`,fullPage:true});await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).last().click();await page.goto(`/epi-entregas/${id}/documento`);await expect(page.locator('.operational-document')).toContainText(f.person.nome);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/b7-documento-${width}.png`,fullPage:true});await page.emulateMedia({media:'print'});await expect(page.locator('.document-actions')).toBeHidden();await page.pdf({path:`test-results/b7-documento-${width}.pdf`,format:'A4'})})

test('B7 quantidade decimal em duas entregas UI termina com saldo zero',async({page,request})=>{const f=await setup(request),p=await call(request,'/produtos','POST',{nome:'EPI fracionado H2 '+f.stamp,codigo:'EP-F-'+f.stamp,unidadeMedida:'UN'});await call(request,'/estoques','POST',{produto:{id:p.id},almoxarifado:{id:f.warehouse.id},quantidade:0});await call(request,`/estoques/entrada?produtoId=${p.id}&almoxarifadoId=${f.warehouse.id}&quantidade=0.3&solicitanteId=${f.person.id}&responsavelId=${f.person.id}`,'PUT');await call(request,'/epis','POST',{produtoId:p.id,ca:'12345',ativo:true,exigeDevolucao:false,permiteRetorno:false});f.products=[p];for(const q of ['0.1','0.2']){await fill(page,f);await page.getByLabel('Quantidade do item 1',{exact:true}).fill(q);await page.getByRole('button',{name:'Confirmar entrega',exact:true}).click();await expect(page).toHaveURL(/epi-entregas\/\d+$/)}expect(await stock(request,f)).toBe(0);const r=await call(request,'/epi-entregas?funcionarioId='+f.person.id);expect(r.totalElements).toBe(2);expect(r.content.map(x=>x.itens[0].quantidade).sort()).toEqual(['0.1','0.2'])})
