import { test, expect } from './security-support.js'
const backend='http://localhost:8081'
let sample
async function call(request,path,options={}) {
 const response=await request.fetch(backend+path,options)
 expect(response.ok(),await response.text()).toBeTruthy()
 return response.json()
}
test.beforeAll(async({request})=>{
 // Safety guard: do not run this test suite against a configurable production URL.
 const marker=Date.now()
 const category=await call(request,'/categorias',{method:'POST',data:{nome:'E2E Materiais '+marker,ativo:true}})
 const unit=await call(request,'/unidades-medida',{method:'POST',data:{nome:'Peça E2E '+marker,sigla:'E'+marker,permiteFracionamento:false,ativo:true}})
 const employee=await call(request,'/funcionarios',{method:'POST',data:{nome:'Operador E2E '+marker,matricula:String(marker),funcao:'Operação'}})
 const warehouse=await call(request,'/almoxarifados',{method:'POST',data:{nome:'Central E2E '+marker}})
 const product=await call(request,'/produtos',{method:'POST',data:{codigo:'TEST-'+marker,nome:'Material E2E '+marker,descricao:'Material para validação isolada',categoriaMaterial:{id:category.id},unidadeMedidaConfigurada:{id:unit.id},ativo:true}})
 await call(request,'/estoques',{method:'POST',data:{produto:{id:product.id},almoxarifado:{id:warehouse.id}}})
 await call(request,`/estoques/entrada?produtoId=${product.id}&almoxarifadoId=${warehouse.id}&quantidade=10&solicitanteId=${employee.id}&responsavelId=${employee.id}`,{method:'PUT'})
 const solicitation=await call(request,`/solicitacoes?solicitanteId=${employee.id}&almoxarifadoId=${warehouse.id}`,{method:'POST'})
 await call(request,`/solicitacoes/${solicitation.id}/itens?produtoId=${product.id}&quantidade=2`,{method:'POST'})
 const rejected=await call(request,`/solicitacoes?solicitanteId=${employee.id}&almoxarifadoId=${warehouse.id}`,{method:'POST'})
 sample={category,unit,employee,warehouse,product,solicitation,rejected,marker}
})
test('desktop: dashboard, cadastros, produto, aprovação e rejeição reais',async({page,request})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 await page.setViewportSize({width:1440,height:1000})
 await page.goto('/')
 await expect(page.getByRole('heading',{name:'Central operacional'})).toBeVisible()
 await expect(page.getByText('Produtos cadastrados')).toBeVisible()
 await expect(page.getByRole('heading',{name:/Solicitações pendentes/})).toBeVisible()
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true})
 for(const [path,title] of [['/categorias','Categorias'],['/unidades','Unidades de medida'],['/almoxarifados','Almoxarifados'],['/funcionarios','Funcionários']]){
  await page.goto(path);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible()
  await expect(page.locator('tbody tr').first()).toBeVisible()
 }
 await page.goto('/categorias');await page.getByRole('button',{name:'Novo cadastro'}).click()
 await page.getByLabel('Nome *',{exact:true}).fill('Categoria visual '+sample.marker)
 await page.getByRole('button',{name:'Salvar cadastro'}).click()
 await expect(page.getByText('Cadastro salvo com sucesso.')).toBeVisible()
 await page.getByRole('row').filter({hasText:'Categoria visual '+sample.marker}).getByRole('button',{name:'Editar'}).click()
 await page.getByLabel('Nome *',{exact:true}).fill('Categoria editada '+sample.marker)
 await page.getByRole('button',{name:'Salvar cadastro'}).click()
 await expect(page.getByRole('cell',{name:'Categoria editada '+sample.marker,exact:true})).toBeVisible()
 await page.goto('/produtos');await page.getByRole('button',{name:'Novo produto'}).click()
 await page.getByLabel('Nome do material *').fill('Produto visual '+sample.marker)
 await page.getByLabel('Código',{exact:true}).fill('VIS-'+sample.marker)
 await page.getByLabel('Categoria *',{exact:true}).selectOption(String(sample.category.id))
 await page.getByLabel('Unidade de medida *',{exact:true}).selectOption(String(sample.unit.id))
 await page.screenshot({path:'test-results/produto-desktop.png',fullPage:true})
 await page.getByRole('button',{name:'Salvar produto'}).click()
 await expect(page.getByText('Produto salvo com sucesso.')).toBeVisible()
 await page.getByRole('row').filter({hasText:'Produto visual '+sample.marker}).getByRole('button',{name:'Editar'}).click()
 await page.getByLabel('Descrição',{exact:true}).fill('Descrição editada pelo navegador '+sample.marker)
 await page.getByRole('button',{name:'Salvar produto'}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await expect(page.getByText('Descrição editada pelo navegador '+sample.marker)).toBeVisible()
 await page.getByLabel('Buscar produtos').fill(sample.product.codigo)
 await expect(page.locator('tbody tr')).toHaveCount(1)
 await expect(page.getByText(sample.product.nome,{exact:true})).toBeVisible()
 await page.goto('/estoques');await expect(page.getByRole('cell',{name:sample.product.nome,exact:true})).toBeVisible()
 await page.goto('/solicitacoes')
 await page.getByRole('row').filter({has:page.getByText('#'+sample.solicitation.id,{exact:true})}).getByRole('button',{name:'Detalhes'}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.getByLabel('Responsável pela aprovação').selectOption(String(sample.employee.id))
 await page.getByRole('button',{name:'Aprovar solicitação'}).click()
 await page.getByRole('button',{name:'Confirmar operação'}).click()
 await expect(page.getByRole('dialog').getByText('Aprovada',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 const stocks=await call(request,'/estoques')
 expect(stocks.find(stock=>stock.produto.id===sample.product.id).quantidade).toBe(10)
 await page.getByRole('row').filter({has:page.getByText('#'+sample.rejected.id,{exact:true})}).getByRole('button',{name:'Detalhes'}).click()
 await page.getByRole('button',{name:'Rejeitar',exact:true}).click()
 await page.getByRole('button',{name:'Confirmar operação'}).click()
 await expect(page.getByRole('dialog').getByText('Rejeitada',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.goto('/movimentacoes');await page.getByLabel('Filtrar tipo').selectOption('ENTRADA')
 await expect(page.getByRole('cell',{name:sample.employee.nome,exact:true}).first()).toBeVisible()
 expect(errors).toEqual([])
})
for(const [name,width] of [['tablet',768],['mobile',390]])test(`${name}: menu, formulários e tabelas sem overflow da página`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.goto('/dashboard')
 await expect(page.getByText('Produtos cadastrados')).toBeVisible()
 await page.getByRole('button',{name:'Abrir menu'}).click()
 await expect(page.getByRole('dialog',{name:'Menu principal'}).getByRole('link',{name:'Produtos',exact:true})).toBeVisible()
 await page.getByRole('dialog',{name:'Menu principal'}).getByRole('link',{name:'Produtos',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Produtos',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Abrir menu'})).toHaveAttribute('aria-expanded','false')
 await page.getByRole('button',{name:'Novo produto'}).click()
 await expect(page.getByLabel('Nome do material *')).toBeVisible()
 await page.screenshot({path:`test-results/produto-${name}.png`,fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.goto('/movimentacoes');await expect(page.locator('tbody tr').first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
})
test('erro HTTP, offline, vazio e página 404',async({page})=>{
 await page.route('**/api/produtos/busca*',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({mensagem:'Conflito de teste'})}))
 await page.goto('/produtos');await expect(page.getByText('Conflito de teste')).toBeVisible();await page.screenshot({path:'test-results/estado-erro.png',fullPage:true})
 await page.unroute('**/api/produtos/busca*')
 await page.route(/^http:\/\/localhost:5173\/api\//,route=>route.request().url().includes('/auth/') ? route.continue() : route.abort())
 await page.goto('/dashboard');await expect(page.getByRole('alert')).toContainText('Não foi possível conectar')
 await expect(page.getByText('Produtos cadastrados')).toHaveCount(0)
 await page.unroute(/^http:\/\/localhost:5173\/api\//)
 await page.goto('/produtos');await page.getByLabel('Buscar produtos').fill('NAO-EXISTE-'+Date.now())
 await expect(page.getByText('Nenhum registro encontrado.')).toBeVisible();await page.screenshot({path:'test-results/estado-vazio.png',fullPage:true})
 await page.goto('/pagina-inexistente');await expect(page.getByRole('heading',{name:'Página não encontrada'})).toBeVisible()
})
