import { test, expect } from '@playwright/test'
const backend = 'http://localhost:8081'
let fixture
async function call(request, path, options = {}) {
  const response = await request.fetch(backend + path, options)
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}
test.beforeAll(async ({ request }) => {
  const stamp = Date.now()
  const category = await call(request, '/categorias', { method: 'POST', data: { nome: 'Operacional ' + stamp, ativo: true } })
  const unit = await call(request, '/unidades-medida', { method: 'POST', data: { nome: 'Peças operacionais ' + stamp, sigla: 'P' + stamp, permiteFracionamento: false, ativo: true } })
  const fraction = await call(request, '/unidades-medida', { method: 'POST', data: { nome: 'Metros operacionais ' + stamp, sigla: 'M' + stamp, permiteFracionamento: true, ativo: true } })
  const employee = await call(request, '/funcionarios', { method: 'POST', data: { nome: 'Solicitante operacional ' + stamp, matricula: 'S' + stamp } })
  const responsible = await call(request, '/funcionarios', { method: 'POST', data: { nome: 'Responsável operacional ' + stamp, matricula: 'R' + stamp } })
  const warehouse = await call(request, '/almoxarifados', { method: 'POST', data: { nome: 'Almoxarifado operacional ' + stamp } })
  const product = await call(request, '/produtos', { method: 'POST', data: { codigo: 'OP-' + stamp, nome: 'Válvula operacional ' + stamp, descricao: 'Aço industrial', ativo: true, categoriaMaterial: { id: category.id }, unidadeMedidaConfigurada: { id: unit.id } } })
  const fractionalProduct = await call(request, '/produtos', { method: 'POST', data: { codigo: 'FR-' + stamp, nome: 'Cabo operacional ' + stamp, ativo: true, categoriaMaterial: { id: category.id }, unidadeMedidaConfigurada: { id: fraction.id } } })
  fixture = { stamp, employee, responsible, warehouse, product, fractionalProduct }
})
async function identifyRequest(page) {
  await page.getByRole('button', { name: 'Nova solicitação', exact: true }).click()
  await page.getByLabel('Solicitante *', { exact: true }).selectOption(String(fixture.employee.id))
  await page.getByLabel('Almoxarifado *', { exact: true }).selectOption(String(fixture.warehouse.id))
}
async function addItem(page, product, amount) {
  await page.getByLabel('Pesquisar catálogo', { exact: true }).fill(product.codigo)
  await page.getByLabel('Produto *', { exact: true }).selectOption(String(product.id))
  await page.getByLabel('Quantidade', { exact: true }).fill(String(amount))
  await page.getByRole('button', { name: 'Adicionar item', exact: true }).click()
}
test('nova solicitação: pesquisar catálogo, validar fração, adicionar/remover e salvar múltiplos itens', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/solicitacoes'); await identifyRequest(page)
  await addItem(page, fixture.product, 1.5)
  await expect(page.getByText('Esta unidade permite somente quantidades inteiras.')).toBeVisible()
  await page.getByLabel('Quantidade', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Adicionar item', exact: true }).click()
  await addItem(page, fixture.product, 3)
  await page.getByRole('button', { name: 'Remover item 2', exact: true }).click()
  await expect(page.getByRole('button', { name: /Remover item/ })).toHaveCount(1)
  await addItem(page, fixture.fractionalProduct, 0.5)
  await page.screenshot({ path: 'test-results/nova-solicitacao-desktop.png' })
  await page.getByRole('button', { name: 'Criar solicitação', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: /^Solicitação #/ })).toBeVisible()
  await expect(page.getByRole('dialog').getByText(fixture.product.codigo, { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').getByText(fixture.fractionalProduct.codigo, { exact: true })).toBeVisible()
  const heading = await page.getByRole('dialog').getByRole('heading', { level: 2 }).innerText()
  const id = Number(heading.match(/#(\d+)/)[1])
  const record = await call(request, '/solicitacoes/' + id)
  expect(record.itens.map(item => item.quantidade)).toEqual([2, 0.5])
  fixture.requestId = id
  await page.getByRole('button', { name: 'Fechar', exact: true }).click()
  await page.getByLabel('Pesquisar solicitações').fill(fixture.fractionalProduct.codigo)
  await page.getByLabel('Filtrar status').selectOption('PENDENTE')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('Pesquisar solicitações').fill('#' + id)
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('Filtrar status').selectOption('APROVADA')
  await expect(page.getByText('Nenhum registro encontrado.')).toBeVisible()
})
test('falha intermediária: conferir e continuar sem duplicar solicitação ou itens', async ({ page, request }) => {
  let additions = 0
  await page.route(/\/api\/solicitacoes\/\d+\/itens\?/, async route => {
    if (++additions === 2) await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ mensagem: 'Item não recebido na validação' }) })
    else await route.continue()
  })
  await page.goto('/solicitacoes'); await identifyRequest(page)
  await addItem(page, fixture.product, 2); await addItem(page, fixture.fractionalProduct, 0.25)
  await page.getByRole('button', { name: 'Criar solicitação', exact: true }).click()
  await expect(page.getByText('Item não recebido na validação')).toBeVisible()
  const progress = await page.getByRole('dialog').getByRole('status').innerText()
  const id = Number(progress.match(/#(\d+)/)[1])
  expect((await call(request, '/solicitacoes/' + id)).itens).toHaveLength(1)
  await page.getByRole('button', { name: 'Conferir itens salvos', exact: true }).click()
  await page.getByRole('button', { name: 'Continuar envio', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Solicitação #' + id, exact: true })).toBeVisible()
  expect((await call(request, '/solicitacoes/' + id)).itens.map(item => item.quantidade)).toEqual([2, 0.25])
  expect(additions).toBe(3)
})
test('item recebido com resposta perdida: reconciliação confirma sem reenviar', async ({ page, request }) => {
  let additions = 0
  await page.route(/\/api\/solicitacoes\/\d+\/itens\?/, async route => { additions++; await route.fetch(); await route.abort() })
  await page.goto('/solicitacoes'); await identifyRequest(page); await addItem(page, fixture.product, 1)
  await page.getByRole('button', { name: 'Criar solicitação', exact: true }).click()
  await expect(page.getByText('O último item pode ter sido recebido.', { exact: false })).toBeVisible()
  const progress = await page.getByRole('dialog').getByRole('status').innerText()
  const id = Number(progress.match(/#(\d+)/)[1])
  await page.getByRole('button', { name: 'Conferir itens salvos', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Solicitação #' + id, exact: true })).toBeVisible()
  expect(additions).toBe(1); expect((await call(request, '/solicitacoes/' + id)).itens).toHaveLength(1)
})
async function identifyMovement(page, action) {
  await page.getByRole('button', { name: action, exact: true }).click()
  await page.getByLabel('Pesquisar catálogo', { exact: true }).fill(fixture.product.codigo)
  await page.getByLabel('Produto *', { exact: true }).selectOption(String(fixture.product.id))
  await page.getByLabel('Almoxarifado *', { exact: true }).selectOption(String(fixture.warehouse.id))
  await page.getByLabel('Solicitante *', { exact: true }).selectOption(String(fixture.employee.id))
  await page.getByLabel('Responsável *', { exact: true }).selectOption(String(fixture.responsible.id))
}
test('entrada/saída reais: novo estoque, quantidade inválida, saldo insuficiente e histórico', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/estoques'); await identifyMovement(page, 'Registrar entrada')
  await expect(page.getByText('Estoque não cadastrado', { exact: true })).toBeVisible()
  await page.getByLabel('Criar estoque zerado para este produto e almoxarifado', { exact: true }).check()
  await page.getByLabel('Quantidade *', { exact: true }).fill('1.5')
  await page.getByRole('button', { name: 'Revisar entrada', exact: true }).click()
  await expect(page.getByText('Esta unidade permite somente quantidades inteiras.')).toBeVisible()
  await page.getByLabel('Quantidade *', { exact: true }).fill('7')
  await page.getByRole('button', { name: 'Revisar entrada', exact: true }).click()
  await page.screenshot({ path: 'test-results/entrada-desktop.png' })
  await page.getByRole('button', { name: 'Confirmar movimentação', exact: true }).click()
  await expect(page.getByText('Entrada registrada com sucesso.')).toBeVisible()
  await page.getByLabel('Pesquisar estoque').fill(fixture.product.codigo)
  await page.getByLabel('Filtrar almoxarifado').selectOption(String(fixture.warehouse.id))
  await expect(page.locator('tbody tr')).toHaveCount(1)
  expect((await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.warehouse.id}`)).quantidade).toBe(7)
  await identifyMovement(page, 'Registrar saída')
  await page.getByLabel('Quantidade *', { exact: true }).fill('8')
  await page.getByRole('button', { name: 'Revisar saída', exact: true }).click()
  await expect(page.getByText('A quantidade de saída é superior ao saldo disponível.')).toBeVisible()
  await page.getByLabel('Quantidade *', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Revisar saída', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar movimentação', exact: true }).click()
  await expect(page.getByText('Saída registrada com sucesso.')).toBeVisible()
  expect((await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.warehouse.id}`)).quantidade).toBe(5)
  await page.goto('/movimentacoes'); await page.getByLabel('Pesquisar movimentações').fill(fixture.product.codigo)
  await page.getByLabel('Filtrar tipo').selectOption('SAIDA')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.getByRole('cell', { name: fixture.responsible.nome, exact: true })).toBeVisible()
  const movements = await call(request, '/movimentacoes/produto/' + fixture.product.id)
  const date = movements[0].dataHora.slice(0, 10)
  await page.getByLabel('De', { exact: true }).fill(date); await page.getByLabel('Até', { exact: true }).fill(date)
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('Pesquisar movimentações').fill(fixture.responsible.nome)
  await expect(page.locator('tbody tr')).toHaveCount(1)
})
for (const [name, width] of [['tablet', 768], ['mobile', 390]]) test(`${name}: novos formulários, itens e pesquisas sem overflow`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/solicitacoes'); await identifyRequest(page); await addItem(page, fixture.product, 2); await addItem(page, fixture.fractionalProduct, 0.5)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: `test-results/nova-solicitacao-${name}.png` })
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  for (const action of ['Registrar entrada', 'Registrar saída']) {
    await page.goto('/estoques'); await identifyMovement(page, action)
    await page.getByLabel('Quantidade *', { exact: true }).fill('1')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await page.screenshot({ path: `test-results/${action === 'Registrar entrada' ? 'entrada' : 'saida'}-${name}.png` })
    await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  for (const path of ['/solicitacoes', '/estoques', '/movimentacoes']) {
    await page.goto(path); await expect(page.locator('main input[type=search]').first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  }
})
