import { test, expect } from './security-support.js'
const backend = 'http://localhost:8081'
let fixture
async function call(request, path, options = {}) {
  const response = await request.fetch(backend + path, options)
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}
test.beforeAll(async ({ request }) => {
  const stamp = Date.now()
  const category = await call(request, '/categorias', { method: 'POST', data: { nome: 'Transferências ' + stamp, ativo: true } })
  const unit = await call(request, '/unidades-medida', { method: 'POST', data: { nome: 'Peça B2 ' + stamp, sigla: 'U' + stamp, permiteFracionamento: false, ativo: true } })
  const fraction = await call(request, '/unidades-medida', { method: 'POST', data: { nome: 'Metro B2 ' + stamp, sigla: 'M' + stamp, permiteFracionamento: true, ativo: true } })
  const responsible = await call(request, '/funcionarios', { method: 'POST', data: { nome: 'Responsável B2 ' + stamp, matricula: 'B2' + stamp } })
  const origin = await call(request, '/almoxarifados', { method: 'POST', data: { nome: 'Central B2 ' + stamp } })
  const destination = await call(request, '/almoxarifados', { method: 'POST', data: { nome: 'Obra B2 ' + stamp } })
  const createProduct = (codigo, nome, medida) => call(request, '/produtos', { method: 'POST', data: { codigo: codigo + stamp, nome: nome + stamp, descricao: 'Material de teste H2', ativo: true, categoriaMaterial: { id: category.id }, unidadeMedidaConfigurada: { id: medida.id } } })
  const product = await createProduct('B2-', 'Válvula B2 ', unit)
  const fractionalProduct = await createProduct('B2F-', 'Cabo B2 ', fraction)
  const createStock = (produto, place) => call(request, '/estoques', { method: 'POST', data: { produto: { id: produto.id }, almoxarifado: { id: place.id }, quantidade: 0 } })
  const stock = await createStock(product, origin); await createStock(product, destination); await createStock(fractionalProduct, origin)
  for (const [produto, place, amount] of [[product, origin, 10], [product, destination, 2], [fractionalProduct, origin, 5]]) {
    await call(request, `/estoques/entrada?produtoId=${produto.id}&almoxarifadoId=${place.id}&quantidade=${amount}&solicitanteId=${responsible.id}&responsavelId=${responsible.id}`, { method: 'PUT' })
  }
  fixture = { stamp, responsible, origin, destination, product, fractionalProduct, stock }
})
async function startTransfer(page) {
  await page.goto('/transferencias')
  await page.getByRole('button', { name: 'Nova transferência', exact: true }).click()
  await page.getByLabel('Almoxarifado de origem *', { exact: true }).selectOption(String(fixture.origin.id))
  await page.getByLabel('Almoxarifado de destino *', { exact: true }).selectOption(String(fixture.destination.id))
  await page.getByLabel('Responsável *', { exact: true }).selectOption(String(fixture.responsible.id))
}
async function selectProduct(page, product = fixture.product) {
  await page.getByLabel('Pesquisar catálogo', { exact: true }).fill(product.codigo)
  await page.getByLabel('Produto *', { exact: true }).selectOption(String(product.id))
  await expect(page.getByRole('button', { name: 'Adicionar produto', exact: true })).toBeEnabled()
}
async function addProduct(page, product, amount) {
  await selectProduct(page, product)
  await page.getByLabel('Quantidade a transferir', { exact: true }).fill(String(amount))
  await page.getByRole('button', { name: 'Adicionar produto', exact: true }).click()
}
async function noOverflow(page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
}
test('estoque: limites, validação, saldo preservado e alerta com sugestão', async ({ page, request }) => {
  await page.goto('/estoques')
  await page.getByLabel('Pesquisar estoque').fill(fixture.product.codigo)
  await page.getByLabel('Filtrar almoxarifado').selectOption(String(fixture.origin.id))
  await page.getByRole('button', { name: 'Configurar limites', exact: true }).click()
  await page.getByLabel('Estoque mínimo', { exact: true }).fill('10')
  await page.getByLabel('Estoque máximo', { exact: true }).fill('9')
  await page.getByRole('button', { name: 'Salvar limites', exact: true }).click()
  await expect(page.getByText('O máximo não pode ser menor que o mínimo.')).toBeVisible()
  await page.getByLabel('Estoque máximo', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Salvar limites', exact: true }).click()
  await expect(page.getByText('Limites configurados com sucesso.')).toBeVisible()
  await expect(page.getByText('Baixo', { exact: true })).toBeVisible()
  await page.getByLabel('Filtrar situação').selectOption('attention')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.getByRole('columnheader', { name: 'Reposição sugerida' })).toBeVisible()
  const stock = await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.origin.id}`)
  expect(stock.quantidade).toBe(10); expect(stock.estoqueMinimo).toBe(10); expect(stock.estoqueMaximo).toBe(20)
  const alerts = await call(request, `/estoques/alertas?produtoId=${fixture.product.id}&almoxarifadoId=${fixture.origin.id}`)
  expect(alerts).toHaveLength(1); expect(alerts[0].quantidadeSugerida).toBe(10)
})
test('dashboard mostra alerta real e abre a visão de atenção', async ({ page }) => {
  await page.goto('/dashboard')
  const section = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Estoque baixo' }) })
  await expect(section.getByText(fixture.product.nome, { exact: true })).toBeVisible()
  await section.getByRole('link', { name: 'Consultar alertas' }).click()
  await expect(page.getByLabel('Filtrar situação')).toHaveValue('attention')
})
test('transferência completa: confirmação, vários itens, detalhes, saldos e movimentações', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await startTransfer(page)
  await addProduct(page, fixture.product, 3); await addProduct(page, fixture.fractionalProduct, 0.5)
  await page.getByLabel('Observação opcional').fill('Conferência operacional B2')
  await page.getByRole('button', { name: 'Revisar transferência', exact: true }).click()
  await expect(page.getByText('Confirmar transferência?', { exact: true })).toBeVisible()
  await expect(page.getByText('Esta operação irá registrar saída no almoxarifado de origem e entrada no almoxarifado de destino.')).toBeVisible()
  await page.screenshot({ path: 'test-results/transferencia-confirmacao-desktop.png' })
  await page.getByRole('button', { name: 'Confirmar transferência', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: /^Transferência #/ })).toBeVisible()
  const title = await dialog.getByRole('heading', { level: 2 }).innerText(); fixture.transferId = Number(title.match(/#(\d+)/)[1])
  await expect(dialog.getByText('Concluída', { exact: true })).toBeVisible()
  await expect(dialog.locator('tbody tr')).toHaveCount(2)
  await expect(page.getByText(`Transferência #${fixture.transferId} concluída com sucesso.`)).toBeVisible()
  expect((await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.origin.id}`)).quantidade).toBe(7)
  expect((await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.destination.id}`)).quantidade).toBe(5)
  expect((await call(request, `/estoques/produto/${fixture.fractionalProduct.id}/almoxarifado/${fixture.destination.id}`)).quantidade).toBe(0.5)
  await page.screenshot({ path: 'test-results/transferencia-detalhes-desktop.png' })
  await dialog.getByRole('link', { name: 'Ver movimentações' }).click()
  await expect(page).toHaveURL(new RegExp('transferenciaId=' + fixture.transferId))
  await expect(page.locator('tbody tr')).toHaveCount(4)
  const history = await call(request, `/transferencias/${fixture.transferId}/movimentacoes`)
  expect(history).toHaveLength(4)
  expect(history.map(row => row.tipo)).toEqual(['SAIDA', 'ENTRADA', 'SAIDA', 'ENTRADA'])
  expect(history.every(row => row.transferenciaId === fixture.transferId && row.origemId === fixture.origin.id && row.destinoId === fixture.destination.id && row.responsavel.id === fixture.responsible.id)).toBeTruthy()
})
test('formulário valida fração, saldo, duplicidade, origem e transferência vazia', async ({ page }) => {
  await startTransfer(page)
  await page.getByRole('button', { name: 'Revisar transferência', exact: true }).click()
  await expect(page.getByText('Adicione pelo menos um produto.')).toBeVisible()
  await addProduct(page, fixture.product, 1.5)
  await expect(page.getByText('Esta unidade permite somente quantidades inteiras.')).toBeVisible()
  await page.getByLabel('Quantidade a transferir').fill('999')
  await page.getByRole('button', { name: 'Adicionar produto', exact: true }).click()
  await expect(page.getByText('A quantidade é superior ao saldo disponível na origem.')).toBeVisible()
  await page.getByLabel('Quantidade a transferir').fill('1')
  await page.getByRole('button', { name: 'Adicionar produto', exact: true }).click()
  await addProduct(page, fixture.product, 1)
  await expect(page.getByText('Este produto já foi adicionado.')).toBeVisible()
  await page.getByLabel('Almoxarifado de destino *', { exact: true }).selectOption(String(fixture.origin.id))
  await page.getByRole('button', { name: 'Revisar transferência', exact: true }).click()
  await expect(page.getByText('Origem e destino devem ser diferentes.')).toBeVisible()
  await page.getByRole('button', { name: 'Remover', exact: true }).click()
  await expect(page.getByText('Nenhum produto adicionado.')).toBeVisible()
})
test('erro de negócio do backend conserva rascunho e não altera saldo', async ({ page, request }) => {
  const before = await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.origin.id}`)
  await page.route('**/api/transferencias', async route => {
    if (route.request().method() === 'POST') await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ mensagem: 'Saldo alterado por outra operação.' }) })
    else await route.continue()
  })
  await startTransfer(page); await addProduct(page, fixture.product, 1)
  await page.getByRole('button', { name: 'Revisar transferência', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar transferência', exact: true }).click()
  await expect(page.getByText('Saldo alterado por outra operação.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Revisar transferência', exact: true })).toBeEnabled()
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(1)
  expect((await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.origin.id}`)).quantidade).toBe(before.quantidade)
})
test('resposta perdida permite consultar a mesma transferência sem duplicar saldos', async ({ page, request }) => {
  let writes = 0
  const keys = [], bodies = []
  const before = await call(request, `/transferencias?origemId=${fixture.origin.id}`)
  const saldoAntes = await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.origin.id}`)
  await page.route('**/api/transferencias', async route => {
    if (route.request().method() === 'POST') {
      writes++; keys.push(route.request().headers()['idempotency-key']); bodies.push(route.request().postData())
      if (writes === 2) { await route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ mensagem: 'Conflito concorrente durante consulta' }) }); return }
      const response = await route.fetch()
      if (writes === 1) await route.abort(); else await route.fulfill({ response })
    }
    else await route.continue()
  })
  await startTransfer(page); await addProduct(page, fixture.product, 1)
  await page.getByRole('button', { name: 'Revisar transferência', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar transferência', exact: true }).click()
  await expect(page.getByText('Não foi possível confirmar o resultado.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Revisar transferência', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Consultar resultado da tentativa', exact: true }).click()
  await expect(page.getByText('Conflito concorrente durante consulta', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Revisar transferência', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Consultar resultado da tentativa', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(writes).toBe(3); expect(keys[0]).toBeTruthy(); expect(new Set(keys).size).toBe(1); expect(new Set(bodies).size).toBe(1)
  expect((await call(request, `/transferencias?origemId=${fixture.origin.id}`)).length).toBe(before.length + 1)
  expect((await call(request, `/estoques/produto/${fixture.product.id}/almoxarifado/${fixture.origin.id}`)).quantidade).toBe(saldoAntes.quantidade - 1)
})
test('filtros e pesquisa encontram transferência e preservam todos os seus itens', async ({ page }) => {
  await page.goto('/transferencias')
  await page.getByLabel('Filtrar origem').selectOption(String(fixture.origin.id))
  await page.getByLabel('Filtrar destino').selectOption(String(fixture.destination.id))
  await page.getByLabel('Filtrar produto').selectOption(String(fixture.fractionalProduct.id))
  await page.getByLabel('Pesquisar transferências').fill('#' + fixture.transferId)
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Detalhes', exact: true }).click()
  await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(2)
  await page.getByRole('button', { name: 'Fechar', exact: true }).first().click()
  await page.getByLabel('Pesquisar transferências').fill('inexistente')
  await expect(page.getByText('Nenhuma transferência encontrada.')).toBeVisible()
})
for (const width of [1440, 768, 390]) {
  test(`estoque, dashboard e transferências utilizáveis sem overflow em ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/estoques?atencao=true'); await expect(page.getByRole('heading', { name: 'Estoque', exact: true })).toBeVisible()
    await page.getByLabel('Pesquisar estoque').fill(fixture.product.codigo)
    await noOverflow(page); await page.screenshot({ path: `test-results/estoque-b2-${width}.png` })
    await page.locator('tbody tr').first().getByRole('button', { name: 'Configurar limites' }).click()
    await expect(page.getByLabel('Estoque mínimo', { exact: true })).toBeVisible(); await noOverflow(page)
    await page.screenshot({ path: `test-results/limites-b2-${width}.png` }); await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
    await page.goto('/dashboard'); await expect(page.getByRole('heading', { name: 'Estoque baixo' })).toBeVisible(); await noOverflow(page)
    await page.screenshot({ path: `test-results/dashboard-b2-${width}.png` })
    await startTransfer(page); await addProduct(page, fixture.product, 1)
    await noOverflow(page); await page.screenshot({ path: `test-results/transferencia-b2-${width}.png` })
    await page.getByRole('button', { name: 'Revisar transferência', exact: true }).click()
    await expect(page.getByText('Confirmar transferência?', { exact: true })).toBeVisible(); await noOverflow(page)
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
    await page.goto(`/transferencias?transferenciaId=${fixture.transferId}`)
    await expect(page.getByRole('dialog').getByRole('heading', { name: `Transferência #${fixture.transferId}`, exact: true })).toBeVisible(); await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(2); await noOverflow(page)
    await page.screenshot({ path: `test-results/transferencia-detalhes-${width}.png` })
  })
}
