import { test, expect, fixtures, protectedRequest } from './security-support.js'
const base='http://localhost:8081'
async function call(request,path,method='GET',data){const r=await request.fetch(base+path,{method,...(data?{data}:{} )});expect(r.ok(),path+' status '+r.status()).toBeTruthy();return r.json()}
async function setup(request){const stamp=Date.now()+'-'+Math.random().toString(36).slice(2,5);const obra=await call(request,'/obras','POST',{codigo:'OB-'+stamp,nome:'Obra UI '+stamp,cliente:'Cliente H2'});const centro=await call(request,'/centros-custo','POST',{codigo:'CC-'+stamp,nome:'Centro UI '+stamp,tipo:'OBRA',ativo:true,obraId:obra.id});const os=await call(request,'/ordens-servico','POST',{obraId:obra.id,centroCustoId:centro.id,titulo:'Serviço UI '+stamp});return {stamp,obra,centro,os}}

async function loginUi(page,profile){
 await page.context().clearCookies();await page.goto('/login');await page.getByLabel('Usuário',{exact:true}).fill(fixtures[profile].username);await page.getByLabel('Senha',{exact:true}).fill(fixtures[profile].password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/dashboard$/)
}

async function setupUi(page,request){
 const stamp=Date.now()+'-'+Math.random().toString(36).slice(2,5)
 await page.goto('/obras');await page.getByRole('button',{name:'Novo cadastro',exact:true}).click();await page.getByLabel('Código',{exact:true}).fill('OB-'+stamp);await page.getByLabel('Nome',{exact:true}).fill('Obra GESTOR '+stamp);await page.getByRole('button',{name:'Salvar cadastro',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible()
 const obra=(await call(request,'/obras?termo=OB-'+stamp)).content[0]
 await page.goto('/centros-custo');await page.getByRole('button',{name:'Novo cadastro',exact:true}).click();const centerDialog=page.getByRole('dialog');await centerDialog.getByLabel('Código',{exact:true}).fill('CC-'+stamp);await centerDialog.getByLabel('Nome',{exact:true}).fill('Centro GESTOR '+stamp);await centerDialog.getByLabel('Tipo',{exact:true}).selectOption('OBRA');await centerDialog.getByLabel('Obra',{exact:true}).selectOption(String(obra.id));await centerDialog.getByRole('button',{name:'Salvar cadastro',exact:true}).click();await expect(centerDialog).not.toBeVisible()
 const centro=(await call(request,'/centros-custo?termo=CC-'+stamp)).content[0]
 await page.goto('/ordens-servico');await page.getByRole('button',{name:'Novo cadastro',exact:true}).click();const osDialog=page.getByRole('dialog');await osDialog.getByLabel('Título',{exact:true}).fill('Serviço GESTOR '+stamp);await osDialog.getByLabel('Obra',{exact:true}).selectOption(String(obra.id));await osDialog.getByLabel('Centro de custo',{exact:true}).selectOption(String(centro.id));await osDialog.getByRole('button',{name:'Salvar cadastro',exact:true}).click();await expect(osDialog).not.toBeVisible()
 const os=(await call(request,'/ordens-servico?termo='+stamp)).content[0]
 return {stamp,obra,centro,os}
}

for(const profile of ['ADMIN','GESTOR'])test('B5 ciclo contextual completo preserva entrada e consumo separados '+profile,async({page,request:seedRequest})=>{
 let request=seedRequest;
 if(profile==='GESTOR'){await page.context().clearCookies();await page.goto('/login');await page.getByLabel('Usuário',{exact:true}).fill(fixtures.GESTOR.username);await page.getByLabel('Senha',{exact:true}).fill(fixtures.GESTOR.password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/dashboard$/);request=protectedRequest(page.request)}
 test.setTimeout(90000);const f=profile==='GESTOR'?await setupUi(page,request):await setup(request);const product=await call(seedRequest,'/produtos','POST',{codigo:'B5-'+f.stamp,nome:'Material B5 '+f.stamp,unidadeMedida:'UN'});const person=await call(seedRequest,'/funcionarios','POST',{nome:'Operador B5 '+f.stamp,matricula:'B5-'+f.stamp});const warehouse=await call(seedRequest,'/almoxarifados','POST',{nome:'Central B5 '+f.stamp});const supplier=await call(seedRequest,'/fornecedores','POST',{nome:'Fornecedor B5 '+f.stamp,tipoPessoa:'PJ'});
 await page.goto('/solicitacoes');await page.getByRole('button',{name:'Nova solicitação',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Solicitante *',{exact:true}).selectOption(String(person.id));await dialog.getByLabel('Almoxarifado *',{exact:true}).selectOption(String(warehouse.id));await dialog.getByLabel('Obra',{exact:true}).selectOption(String(f.obra.id));await dialog.getByLabel('Ordem de serviço',{exact:true}).selectOption(String(f.os.id));await expect(dialog.getByLabel('Centro de custo',{exact:true})).toHaveValue(String(f.centro.id));
 // Demand items use the existing catalog picker; capture actual created demand rather than infer IDs.
 await dialog.getByLabel('Pesquisar catálogo',{exact:true}).fill(product.codigo);await dialog.getByLabel('Produto *',{exact:true}).selectOption(String(product.id));await dialog.getByLabel('Quantidade',{exact:true}).fill('4');await dialog.getByRole('button',{name:'Adicionar item',exact:true}).click();await dialog.getByRole('button',{name:'Criar solicitação',exact:true}).click();await expect(dialog.locator('.context-value')).toContainText(f.os.numero);const s=await call(request,'/solicitacoes?ordemServicoId='+f.os.id);expect(s).toHaveLength(1);const demand=s[0],item=demand.itens[0];
 await dialog.getByLabel('Responsável pela aprovação').selectOption(String(person.id));await dialog.getByRole('button',{name:'Aprovar solicitação',exact:true}).click();await dialog.getByRole('button',{name:'Confirmar operação',exact:true}).click();await expect(dialog.getByText('Aprovada',{exact:true})).toBeVisible();
 const n=await (await request.post(base+'/necessidades-compra',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{itemSolicitacaoId:item.id,responsavelId:person.id}})).json();expect(n.contexto.obraId).toBe(f.obra.id);
 await page.goto('/necessidades-compra?solicitacaoId='+demand.id);await page.getByLabel('Selecionar necessidade '+n.id,{exact:true}).check();await page.getByRole('button',{name:'Criar pedido das necessidades selecionadas'}).click();await page.getByLabel('Fornecedor *',{exact:true}).selectOption(String(supplier.id));await page.getByLabel('Valor unitário (R$) *').fill('3.1250');await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page).toHaveURL(/pedidos-compra\/\d+$/);const id=Number(page.url().split('/').pop());await page.getByRole('button',{name:'Submeter para aprovação',exact:true}).click();await page.getByRole('button',{name:'Confirmar submissão',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await page.getByRole('button',{name:'Aprovar pedido',exact:true}).click();await page.getByRole('button',{name:'Confirmar aprovação',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();
 if(profile==='GESTOR'){await loginUi(page,'ALMOXARIFE');await page.goto('/pedidos-compra/'+id)}
 await page.getByRole('button',{name:'Registrar recebimento',exact:true}).click();await page.getByLabel('Responsável físico *',{exact:true}).selectOption(String(person.id));await page.getByLabel('Receber '+product.nome,{exact:true}).fill('4');await page.getByRole('button',{name:'Revisar recebimento',exact:true}).click();await page.getByRole('button',{name:'Confirmar entrada no estoque',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();expect((await call(request,`/solicitacoes/${demand.id}/operacao`)).status).toBe('APROVADA');expect((await call(request,`/obras/${f.obra.id}/resumo`)).materiaisConsumidos).toEqual([]);
 await page.goto('/solicitacoes?solicitacaoId='+demand.id);await page.getByLabel('Responsável pela separação').selectOption(String(person.id));await page.getByRole('button',{name:'Iniciar separação',exact:true}).click();await page.getByRole('button',{name:'Confirmar operação',exact:true}).click();await expect(page.getByRole('dialog').getByText('Em separação',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Registrar atendimento',exact:true}).click();await page.getByLabel('Entregar item #'+item.id,{exact:true}).fill('4');await page.getByLabel('Responsável pelo atendimento',{exact:true}).selectOption(String(person.id));await page.getByRole('button',{name:'Revisar atendimento',exact:true}).click();await page.getByRole('button',{name:'Confirmar atendimento',exact:true}).click();await expect(page.getByRole('dialog').getByText('Atendida',{exact:true})).toBeVisible();if(profile==='GESTOR')await loginUi(page,'GESTOR');const summary=await call(request,`/ordens-servico/${f.os.id}/resumo`);expect(summary.quantidadePedidos).toBe(1);expect(summary.materiaisConsumidos[0][3]).toBe(4);expect(summary.custoConsumido).toBeNull();await page.goto('/obras/'+f.obra.id);await expect(page.getByRole('heading',{name:'Consumo quantitativo confirmado',exact:true})).toBeVisible();await page.goto(`/ordens-servico/${f.os.id}/documento`);await expect(page.locator('.operational-document')).toContainText(f.obra.nome);
})
test('B5 cadastros e transições estruturais na interface',async({page,request})=>{await page.goto('/obras');await page.getByRole('button',{name:'Novo cadastro',exact:true}).click();const code='UI-'+Date.now();await page.getByLabel('Código',{exact:true}).fill(code);await page.getByLabel('Nome',{exact:true}).fill('Obra cadastrada pela tela');await page.getByRole('button',{name:'Salvar cadastro',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await page.getByLabel('Pesquisar código, número ou nome').fill(code);await page.getByRole('link',{name:code,exact:true}).click();await page.getByRole('button',{name:'ATIVA',exact:true}).click();await page.getByRole('button',{name:'Confirmar status',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.locator('.badge-ativa')).toBeVisible();const f=await setup(request);await page.goto('/ordens-servico/'+f.os.id);await page.getByRole('button',{name:'EM ANDAMENTO',exact:true}).click();await page.getByRole('button',{name:'Confirmar status',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.locator('.badge-em_andamento')).toBeVisible()})
for(const width of [1440,768,390])test('B5 estrutura, seleção e ficha A4 sem overflow '+width,async({page,request})=>{const f=await setup(request);await page.setViewportSize({width,height:900});for(const path of ['/obras','/ordens-servico','/centros-custo','/obras/'+f.obra.id,'/ordens-servico/'+f.os.id,'/centros-custo/'+f.centro.id,`/ordens-servico/${f.os.id}/documento`]){await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}await expect(page.locator('.operational-document')).toContainText(f.os.numero);await page.emulateMedia({media:'print'});await expect(page.locator('.document-actions')).toBeHidden();expect(await page.locator('.sidebar').count()).toBe(0);await page.pdf({path:`test-results/b5-os-${width}.pdf`,format:'A4'});await page.emulateMedia({media:'screen'});await page.goto('/ordens-servico');await page.getByRole('button',{name:'Novo cadastro',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('Obra',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`test-results/b5-form-${width}.png`,fullPage:true})})
for(const profile of ['GESTOR','ALMOXARIFE','CONSULTA'])test('B5 gestão e leitura respeitam perfil '+profile,async({browser,request})=>{const context=await browser.newContext({baseURL:'http://localhost:5173'});const page=await context.newPage();await page.goto('/login');await page.getByLabel('Usuário',{exact:true}).fill(fixtures[profile].username);await page.getByLabel('Senha',{exact:true}).fill(fixtures[profile].password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/dashboard$/);for(const path of ['obras','ordens-servico','centros-custo']){await page.goto('/'+path);await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByRole('button',{name:'Novo cadastro',exact:true})).toHaveCount(profile==='GESTOR'?1:0)}if(profile==='GESTOR'){await page.getByRole('button',{name:'Novo cadastro',exact:true}).click();await page.getByLabel('Código',{exact:true}).fill('GESTOR-'+Date.now());await page.getByLabel('Nome',{exact:true}).fill('Centro administrativo gestor H2');await page.getByRole('button',{name:'Salvar cadastro',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible()}await context.close()})
test('B5 incoerência de IDs é recusada pelo backend autenticado',async({request})=>{const a=await setup(request),b=await setup(request);const r=await request.post(base+`/solicitacoes?solicitanteId=1&almoxarifadoId=1&obraId=${a.obra.id}&ordemServicoId=${b.os.id}`);expect(r.status()).toBe(409)})

test('B5 pedido para duas obras mantém origens distintas na tela e nos documentos',async({page,request})=>{const a=await setup(request),b=await setup(request);const prod=await call(request,'/produtos','POST',{codigo:'MULTI-'+a.stamp,nome:'Material multiobra '+a.stamp,unidadeMedida:'UN'});const person=await call(request,'/funcionarios','POST',{nome:'Multiobra '+a.stamp,matricula:'MULTI-'+a.stamp});const warehouse=await call(request,'/almoxarifados','POST',{nome:'Multiobra '+a.stamp});const supplier=await call(request,'/fornecedores','POST',{nome:'Multiobra fornecedor '+a.stamp,tipoPessoa:'PJ'});const needs=[];for(const [f,q] of [[a,2],[b,3]]){const r=await call(request,`/solicitacoes?solicitanteId=${person.id}&almoxarifadoId=${warehouse.id}&ordemServicoId=${f.os.id}`,'POST');const item=await call(request,`/solicitacoes/${r.id}/itens?produtoId=${prod.id}&quantidade=${q}`,'POST');await call(request,`/solicitacoes/${r.id}/aprovar?responsavelId=${person.id}`,'PUT');const n=await request.post(base+'/necessidades-compra',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{itemSolicitacaoId:item.id,responsavelId:person.id}});expect(n.ok()).toBeTruthy();needs.push(await n.json())}const p=await call(request,'/pedidos-compra','POST',{fornecedorId:supplier.id,almoxarifadoId:warehouse.id,itens:[{produtoId:prod.id,quantidade:5,valorUnitario:'2.5',paraEstoque:false,alocacoes:needs.map(n=>({necessidadeId:n.id,quantidade:n.quantidade}))}]});expect(p.itens[0].alocacoes.map(n=>n.contexto.obraId)).toEqual([a.obra.id,b.obra.id]);await page.goto(`/pedidos-compra/${p.id}/documento`);await expect(page.locator('.operational-document')).toContainText(a.os.numero);await expect(page.locator('.operational-document')).toContainText(b.os.numero);for(const f of [a,b]){const list=await call(request,`/pedidos-compra?obraId=${f.obra.id}`);expect(list.content.map(x=>x.id)).toContain(p.id)}const mismatch=await call(request,`/pedidos-compra?obraId=${a.obra.id}&ordemServicoId=${b.os.id}`);expect(mismatch.totalElements).toBe(0)})
test('B5 compra geral recebe sem obra inventada e sem consumo',async({page,request})=>{const f=await setup(request);const prod=await call(request,'/produtos','POST',{codigo:'GERAL-'+f.stamp,nome:'Estoque geral '+f.stamp,unidadeMedida:'UN'});const person=await call(request,'/funcionarios','POST',{nome:'Geral '+f.stamp,matricula:'GERAL-'+f.stamp});const warehouse=await call(request,'/almoxarifados','POST',{nome:'Geral '+f.stamp});const supplier=await call(request,'/fornecedores','POST',{nome:'Geral fornecedor '+f.stamp,tipoPessoa:'PJ'});const p=await call(request,'/pedidos-compra','POST',{fornecedorId:supplier.id,almoxarifadoId:warehouse.id,itens:[{produtoId:prod.id,quantidade:2,valorUnitario:'1.25',paraEstoque:true,alocacoes:[]}]});await call(request,`/pedidos-compra/${p.id}/submeter`,'PUT');await call(request,`/pedidos-compra/${p.id}/aprovar`,'PUT');const r=await request.post(base+`/pedidos-compra/${p.id}/recebimentos`,{headers:{'Idempotency-Key':crypto.randomUUID()},data:{almoxarifadoId:warehouse.id,responsavelId:person.id,itens:[{itemPedidoId:p.itens[0].id,quantidade:2}]}});expect(r.ok()).toBeTruthy();const receipt=await r.json();expect(receipt.itens[0].contexto).toBeNull();await page.goto(`/recebimentos-compra/${receipt.id}/documento`);await expect(page.locator('.operational-document')).toContainText('Sem contexto');const summary=await call(request,`/obras/${f.obra.id}/resumo`);expect(summary.quantidadePedidos).toBe(0);expect(summary.materiaisConsumidos).toEqual([])})

test('B5 comprovante parcial mostra somente o contexto da quantidade recebida',async({page,request})=>{
 const a=await setup(request),b=await setup(request);
 const prod=await call(request,'/produtos','POST',{codigo:'MISTO-'+a.stamp,nome:'Material misto '+a.stamp,unidadeMedida:'UN'});
 const person=await call(request,'/funcionarios','POST',{nome:'Misto '+a.stamp,matricula:'MISTO-'+a.stamp});
 const warehouse=await call(request,'/almoxarifados','POST',{nome:'Misto '+a.stamp});
 const supplier=await call(request,'/fornecedores','POST',{nome:'Misto fornecedor '+a.stamp,tipoPessoa:'PJ'});
 const demand=await call(request,`/solicitacoes?solicitanteId=${person.id}&almoxarifadoId=${warehouse.id}&ordemServicoId=${a.os.id}`,'POST');
 const item=await call(request,`/solicitacoes/${demand.id}/itens?produtoId=${prod.id}&quantidade=2`,'POST');
 await call(request,`/solicitacoes/${demand.id}/aprovar?responsavelId=${person.id}`,'PUT');
 const nr=await request.post(base+'/necessidades-compra',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{itemSolicitacaoId:item.id,responsavelId:person.id}});expect(nr.ok()).toBeTruthy();const n=await nr.json();
 const p=await call(request,'/pedidos-compra','POST',{fornecedorId:supplier.id,almoxarifadoId:warehouse.id,itens:[{produtoId:prod.id,quantidade:5,valorUnitario:'1.25',paraEstoque:true,contexto:{ordemServicoId:b.os.id},alocacoes:[{necessidadeId:n.id,quantidade:2}]}]});
 await call(request,`/pedidos-compra/${p.id}/submeter`,'PUT');await call(request,`/pedidos-compra/${p.id}/aprovar`,'PUT');
 for(const [q,expected,absent] of [[2,a.os.numero,b.os.numero],[3,b.os.numero,a.os.numero]]){
  const rr=await request.post(base+`/pedidos-compra/${p.id}/recebimentos`,{headers:{'Idempotency-Key':crypto.randomUUID()},data:{almoxarifadoId:warehouse.id,responsavelId:person.id,itens:[{itemPedidoId:p.itens[0].id,quantidade:q}]}});expect(rr.ok()).toBeTruthy();const r=await rr.json();
  await page.goto(`/recebimentos-compra/${r.id}/documento`);await expect(page.locator('.operational-document')).toContainText(expected);await expect(page.locator('.operational-document')).not.toContainText(absent);
 }
 expect((await call(request,`/solicitacoes/${demand.id}/operacao`)).status).toBe('APROVADA');
 expect((await call(request,`/obras/${b.obra.id}/resumo`)).materiaisConsumidos).toEqual([]);
})

test('B5 filtro de Obra mantém centro corporativo compatível',async({page,request})=>{
 const f=await setup(request);
 const c=await call(request,'/centros-custo','POST',{codigo:'CORP-'+f.stamp,nome:'Centro corporativo '+f.stamp,tipo:'ADMINISTRATIVO',ativo:true});
 const person=await call(request,'/funcionarios','POST',{nome:'Corporativo '+f.stamp,matricula:'CORP-'+f.stamp});
 const warehouse=await call(request,'/almoxarifados','POST',{nome:'Corporativo '+f.stamp});
 const demand=await call(request,`/solicitacoes?solicitanteId=${person.id}&almoxarifadoId=${warehouse.id}&obraId=${f.obra.id}&centroCustoId=${c.id}`,'POST');
 await page.goto('/solicitacoes');await page.getByLabel('Obra',{exact:true}).selectOption(String(f.obra.id));await page.getByLabel('Centro de custo',{exact:true}).selectOption(String(c.id));
 await expect(page.getByRole('row').filter({hasText:'#'+demand.id})).toContainText(c.codigo);
 expect((await call(request,`/solicitacoes?obraId=${f.obra.id}&centroCustoId=${c.id}`)).map(r=>r.id)).toContain(demand.id);
})

test('B5 pesquisa mantém seleções visíveis e troca de Obra limpa OS e centro',async({page,request})=>{
 const a=await setup(request),b=await setup(request)
 await page.goto('/solicitacoes');await page.getByRole('button',{name:'Nova solicitação',exact:true}).click();const dialog=page.getByRole('dialog')
 await dialog.getByLabel('Obra',{exact:true}).selectOption(String(a.obra.id));await dialog.getByLabel('Ordem de serviço',{exact:true}).selectOption(String(a.os.id))
 await dialog.getByLabel('Pesquisar obra',{exact:true}).fill(b.obra.codigo);await dialog.getByLabel('Pesquisar OS',{exact:true}).fill('sem-resultados-auditoria');await dialog.getByLabel('Pesquisar centro de custo',{exact:true}).fill('sem-resultados-auditoria')
 await expect(dialog.getByLabel('Obra',{exact:true})).toHaveValue(String(a.obra.id));await expect(dialog.getByLabel('Obra',{exact:true}).locator('option:checked')).toContainText(a.obra.codigo)
 await expect(dialog.getByLabel('Ordem de serviço',{exact:true}).locator('option:checked')).toContainText(a.os.numero);await expect(dialog.getByLabel('Centro de custo',{exact:true}).locator('option:checked')).toContainText(a.centro.codigo)
 await dialog.getByLabel('Obra',{exact:true}).selectOption(String(b.obra.id));await expect(dialog.getByLabel('Ordem de serviço',{exact:true})).toHaveValue('');await expect(dialog.getByLabel('Centro de custo',{exact:true})).toHaveValue('')
})
