import { useCallback, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { useResource } from '../hooks/useResource'
import { ResourceView, dateTime } from '../components/ui'
import OperationalDocument from '../components/OperationalDocument'
import { assetLabel } from '../utils/assets'
import { ContextDisplay } from '../components/ContextSelector'
export default function AssetDocument({kind='ativos'}) {
 const {id}=useParams(),[generated]=useState(()=>dateTime(new Date().toISOString()))
 const resource=useResource(useCallback(async signal=>{const r=await api.get(kind,id,signal);if(kind==='ativos'){const [local,person]=await Promise.all([r.almoxarifadoId?api.get('almoxarifados',r.almoxarifadoId,signal):null,r.responsavelId?api.get('funcionarios',r.responsavelId,signal):null]);r.almoxarifadoNome=local?.nome;r.responsavelNome=person?.nome}return r},[kind,id]))
 return <main className="document-view"><ResourceView resource={resource}>{r=>{
  const ficha=kind==='ativos',end=r.encerramento
  const fields=ficha?[['Status',assetLabel(r.status)],['Condição',assetLabel(r.condicao)],['Fabricante / modelo',`${r.fabricante||'—'} / ${r.modelo||'—'}`],['Série',r.numeroSerie],['Almoxarifado atual',r.almoxarifadoNome||(r.almoxarifadoId?`Almoxarifado #${r.almoxarifadoId}`:r.contexto?.obraId?'Obra':'Local não informado')],['Responsável atual',r.responsavelNome||(r.responsavelId?`Funcionário #${r.responsavelId}`:'Sem custódia individual')],['Próxima inspeção',r.proximaInspecao]]:[['Situação',r.aberto?'Em aberto':'Concluído'],['Registro',`#${r.id} · ${assetLabel(r.tipo)}`],['Retirada / envio',dateTime(r.dataHora)],['Entregou',r.entreguePorNome],['Recebeu',r.recebidoPorNome],['Usuário autenticado',r.atorNome],['Origem',r.localOrigemNome||'Obra'],['Destino',r.localDestinoNome||'Obra'],['Condição na saída',assetLabel(r.condicaoDepois)],['Previsão de devolução',r.previsaoDevolucao]]
  return <><nav className="document-actions"><Link className="btn secondary" to={`/ativos/${ficha?id:r.ativoId}`}>Voltar ao ativo</Link><button className="btn" onClick={()=>window.print()}>Imprimir / salvar PDF</button></nav><OperationalDocument title={ficha?'Ficha do ativo':kind==='emprestimos'?'Comprovante de empréstimo e devolução':'Comprovante de transferência de ativo'} reference={`${r.codigoPatrimonial}${ficha?'':` · #${r.id}`}`} generatedAt={generated} metadata={fields}><h2>{r.nome||r.ativoNome}</h2><p>Contexto {ficha?'atual':'da origem'}: <ContextDisplay value={ficha?r.contexto:r.contextoOrigem}/></p>{!ficha&&<p>Contexto da destinação: <ContextDisplay value={r.contextoDestino}/></p>}<p className="asset-observation">{r.descricao||r.observacao}</p>{end&&<section><h2>{kind==='emprestimos'?'Devolução confirmada':'Chegada confirmada'}</h2><dl className="document-metadata">{[['Data',dateTime(end.dataHora)],['Entregou',end.entreguePorNome],['Recebeu',end.recebidoPorNome],['Usuário autenticado',end.atorNome],['Condição',assetLabel(end.condicaoDepois)],['Destino',end.localDestinoNome||'Obra']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl><p><ContextDisplay value={end.contextoDestino}/></p><p className="asset-observation">{end.observacao}</p></section>}<p className="document-note">Registro operacional confirmado em tela; não constitui assinatura digital jurídica. Condições registradas não atribuem culpa automaticamente.</p>{ficha&&<p className="document-note">Ficha do cadastro atual. Comprovantes preservam a identificação e o contexto de cada operação histórica.</p>}</OperationalDocument></>
 }}</ResourceView></main>
}
