import { useCallback, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { api, request } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { useResource } from '../hooks/useResource'
import { PageHeader, Card, Field, Modal, Notice, ResourceView, DataTable, Badge, dateTime } from '../components/ui'
import ContextSelector, { ContextDisplay } from '../components/ContextSelector'
import { Pagination } from './Suppliers'
import { conditions, assetStatuses, assetKinds, assetActions, operationBody, assetOperation, assetLabel, assetLocation } from '../utils/assets'
const titles = { criar:'Cadastrar ativo', editar:'Editar identificação', emprestar:'Registrar empréstimo', devolver:'Devolver ativo', transferir:'Enviar transferência', receber:'Confirmar chegada', inspecionar:'Registrar inspeção', inativar:'Inativar ativo', reativar:'Reativar ativo', baixar:'Baixar ativo' }
const blank = { codigoPatrimonial:'', nome:'', descricao:'', fabricante:'', modelo:'', numeroSerie:'', categoriaId:'', dataAquisicao:'', observacao:'' }
export default function Assets({ kind='ativos' }) {
 const { id } = useParams(), [search] = useSearchParams(), auth = useAuth(), cfg=assetKinds[kind]
 const sending=useRef(false)
 const [success,setSuccess]=useState('')
 const [assetTerm,setAssetTerm]=useState(''), [filters,setFilters]=useState({de:'',ate:'',termo:'',status:'',condicao:'',categoriaId:'',funcionarioId:'',almoxarifadoId:'',obraId:'',ordemServicoId:'',centroCustoId:'',aberto:kind==='emprestimos'?'true':'',vencido:search.get('vencido')||'',inspecaoPendente:search.get('inspecaoPendente')||''})
 const [page,setPage]=useState(0),[historyPage,setHistoryPage]=useState(0),[modal,setModal]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(null)
 const resource=useResource(useCallback(signal=>id?api.get('ativos',id,signal):api.list(kind,{...filters,pagina:page},signal),[id,kind,filters,page]))
 const history=useResource(useCallback(signal=>id?api.list(`ativos/${id}/historico`,{pagina:historyPage},signal):Promise.resolve(null),[id,historyPage]))
 const refs=useResource(useCallback(signal=>Promise.all(['funcionarios','almoxarifados','categorias'].map(k=>api.list(k,{},signal))),[]))
 const canReadTransfer=auth.can('TRANSFERENCIA_ATIVO_LER')
 const pendingAsset=id?resource.data:modal?.asset
 const pending=useResource(useCallback(signal=>pendingAsset?.status==='EM_TRANSFERENCIA'&&pendingAsset.pendenciaId&&canReadTransfer?api.get('transferencias-ativos',pendingAsset.pendenciaId,signal):Promise.resolve(null),[pendingAsset?.status,pendingAsset?.pendenciaId,canReadTransfer]))
 const choices=useResource(useCallback(async signal=>{if(!modal||!('ativoId' in form)||modal.asset.id)return null;const p=await api.list('ativos',{tamanho:100,termo:assetTerm},signal);if(form.ativoId&&!p.content.some(a=>String(a.id)===String(form.ativoId)))p.content.unshift(await api.get('ativos',form.ativoId,signal));return p},[modal?.action,modal?.asset.id,assetTerm,form.ativoId]))
 function open(action,a={}) {
  setError('');setSuccess('');setAttempt(null);setAssetTerm('');setModal({action,asset:a})
  if(action==='criar'||action==='editar')setForm({...blank,...Object.fromEntries(Object.keys(blank).map(k=>[k,a[k]??blank[k]])),...(action==='criar'?{almoxarifadoId:'',condicao:'BOM',proximaInspecao:''}:{})})
  else if(action==='emprestar')setForm({ativoId:a.id||'',entreguePorId:'',funcionarioId:'',contexto:{...(a.contexto||{})},condicao:a.condicao||'BOM',previsaoDevolucao:'',observacao:''})
  else if(action==='transferir')setForm({ativoId:a.id||'',entreguePorId:'',almoxarifadoId:'',contexto:{},condicao:a.condicao||'BOM',observacao:''})
  else if(action==='devolver')setForm({devolvidoPorId:a.responsavelId||'',recebidoPorId:'',almoxarifadoId:'',condicao:a.condicao||'BOM',observacao:''})
  else if(action==='receber')setForm({recebidoPorId:'',condicao:a.condicao||'BOM',observacao:''})
  else if(action==='inspecionar')setForm({ativoId:a.id||'',inspetorId:'',condicao:a.condicao||'BOM',resultado:'APROVADO',proximaInspecao:'',observacao:''})
  else setForm({acao:{inativar:'INATIVACAO',reativar:'REATIVACAO',baixar:'BAIXA'}[action],responsavelId:'',motivo:''})
 }
 function close(){if(!busy){setModal(null);setAttempt(null);setError('')}}
 async function save(e) {
  e?.preventDefault();if(sending.current)return;sending.current=true;setBusy(true);setError('')
  let current=attempt
  try {
   if(!current){const body=operationBody(form),action=modal.action;let path,method;
    if(action==='criar'){path='/ativos';method='POST';const {almoxarifadoId,condicao,proximaInspecao,...cadastro}=body;current={path,method,body:{cadastro,almoxarifadoId,condicao,proximaInspecao},key:null}}
    else if(action==='editar')current={path:`/ativos/${modal.asset.id}`,method:'PUT',body,key:null}
    else current={...assetOperation(action,modal.asset.id,modal.asset.pendenciaId),body,key:crypto.randomUUID()}
    setAttempt(current)
   }
   await request(current.path,{method:current.method,body:current.body,...(current.key?{headers:{'Idempotency-Key':current.key}}:{})});setSuccess('Operação confirmada. Estado e histórico atualizados.');setModal(null);setAttempt(null);resource.reload();history.reload();choices.reload();pending.reload()
  }catch(e){setError(e.message);if(e.status&&e.status<500)setAttempt(null)}finally{sending.current=false;setBusy(false)}
 }
 function filter(k,v){setFilters(f=>({...f,[k]:v}));setPage(0)}
 const records=(rows)=> <DataTable rows={rows} columns={[{key:'id',label:'Registro',render:r=><span>#{r.id} · {assetLabel(r.tipo)}</span>},{key:'ativo',label:'Ativo',render:r=><Link to={`/ativos/${r.ativoId}`}>{r.codigoPatrimonial} · {r.ativoNome}</Link>},{key:'situacao',label:'Situação',render:r=>typeof r.aberto==='boolean'?<><span>{r.aberto?'Em aberto':'Concluído'}</span>{r.vencido&&<strong className="asset-overdue">Vencido</strong>}</>:<Badge value={r.statusDepois}/>},{key:'dataHora',label:'Data',render:r=>dateTime(r.dataHora)},{key:'responsavel',label:'Entregou / recebeu',render:r=>`${r.entreguePorNome||'—'} / ${r.recebidoPorNome||'—'}`},{key:'condition',label:'Condição',render:r=>`${assetLabel(r.condicaoAntes)} → ${assetLabel(r.condicaoDepois)}`},{key:'context',label:'Destino',render:r=><><span>{r.localDestinoNome||'—'}</span><br/><ContextDisplay value={r.contextoDestino}/></>},{key:'resultado',label:'Resultado / previsão',render:r=>r.resultado?<Badge value={r.resultado}/>:r.previsaoDevolucao||'—'},{key:'document',label:'Documento',render:r=>['EMPRESTIMO','TRANSFERENCIA'].includes(r.tipo)&&<Link to={`/${r.tipo==='EMPRESTIMO'?'emprestimos':'transferencias-ativos'}/${r.id}/documento`}>Comprovante #{r.id}</Link>}]}/>
 return <><PageHeader eyebrow="ATIVOS" title={id?'Detalhe do ativo':cfg.title} description="Custódia individual, condição física e histórico rastreável.">{id?<Link className="btn secondary" to="/ativos">Voltar aos ativos</Link>:auth.can(cfg.manage)&&<button className="btn" onClick={()=>open(kind==='ativos'?'criar':kind==='emprestimos'?'emprestar':kind==='transferencias-ativos'?'transferir':'inspecionar')}>{kind==='ativos'?'Cadastrar ativo':kind==='emprestimos'?'Registrar empréstimo':kind==='transferencias-ativos'?'Enviar transferência':'Registrar inspeção'}</button>}</PageHeader><Notice error>{modal?null:error}</Notice><Notice>{success}</Notice>
 {!id&&<Card><div className="filters">{kind==='ativos'&&<><Field label="Pesquisar ativos"><input placeholder="Código, nome, marca, série, responsável ou obra" value={filters.termo} onChange={e=>filter('termo',e.target.value)}/></Field><Field label="Status do ativo"><select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">Todos</option>{assetStatuses.map(v=><option key={v} value={v}>{assetLabel(v)}</option>)}</select></Field><Field label="Condição física"><select value={filters.condicao} onChange={e=>filter('condicao',e.target.value)}><option value="">Todas</option>{conditions.map(v=><option key={v} value={v}>{assetLabel(v)}</option>)}</select></Field><Field label="Inspeção pendente"><select value={filters.inspecaoPendente} onChange={e=>filter('inspecaoPendente',e.target.value)}><option value="">Todas</option><option value="true">Pendentes</option><option value="false">Em dia / sem agenda</option></select></Field></>}{kind==='emprestimos'&&<><Field label="Empréstimos em aberto"><select value={filters.aberto} onChange={e=>filter('aberto',e.target.value)}><option value="">Todos</option><option value="true">Em aberto</option><option value="false">Concluídos</option></select></Field><Field label="Prazo de devolução"><select value={filters.vencido} onChange={e=>filter('vencido',e.target.value)}><option value="">Todos</option><option value="true">Vencidos em aberto</option></select></Field></>}
 {kind!=='ativos'&&['de','ate'].map(k=><Field key={k} label={k==='de'?'Data inicial':'Data final'}><input type="date" value={filters[k]} onChange={e=>filter(k,e.target.value)}/></Field>)}<ResourceView resource={refs}>{([people,warehouses,categories])=><><Field label="Filtrar funcionário"><select value={filters.funcionarioId} onChange={e=>filter('funcionarioId',e.target.value)}><option value="">Todos</option>{people.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field>{kind==='ativos'&&<><Field label="Filtrar almoxarifado"><select value={filters.almoxarifadoId} onChange={e=>filter('almoxarifadoId',e.target.value)}><option value="">Todos</option>{warehouses.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field><Field label="Filtrar categoria"><select value={filters.categoriaId} onChange={e=>filter('categoriaId',e.target.value)}><option value="">Todas</option>{categories.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field></>}</>}</ResourceView><details className="asset-context-options"><summary>Filtrar por Obra / OS / centro de custo</summary><ContextSelector filter value={filters} onChange={v=>{setFilters({...filters,...v});setPage(0)}}/></details></div></Card>}
 <ResourceView resource={resource}>{data=>id?<><Card className="asset-current"><h2>{data.codigoPatrimonial} · {data.nome}</h2><Badge value={data.status}/><dl className="document-metadata"><div><dt>Condição física</dt><dd><Badge value={data.condicao}/></dd></div><div><dt>Localização</dt><dd>{data.status==='EM_TRANSFERENCIA'?'Em trânsito; origem: ':''}{assetLocation(data,refs.data?.[1])}<br/><ContextDisplay value={data.contexto}/></dd></div><div><dt>Responsável atual</dt><dd>{data.responsavelId?(refs.data?.[0].find(p=>p.id===data.responsavelId)?.nome||`Funcionário #${data.responsavelId}`):'Sem custódia individual'}</dd></div><div><dt>Fabricante / modelo / série</dt><dd>{[data.fabricante,data.modelo,data.numeroSerie].filter(Boolean).join(' · ')||'—'}</dd></div><div><dt>Próxima inspeção</dt><dd>{data.proximaInspecao||'Não programada'}</dd></div></dl>{data.status==='EM_TRANSFERENCIA'&&<ResourceView resource={pending}>{r=>r&&<Notice>Destino planejado: {r.localDestinoNome||'Obra'} <ContextDisplay value={r.contextoDestino}/>. A localização só muda após confirmar chegada.</Notice>}</ResourceView>}{data.reprovado&&<Notice error>Inspeção reprovada. Novo empréstimo bloqueado até aprovação.</Notice>}{data.inspecaoPendente&&<Notice>Inspeção pendente. Inspecione antes de emprestar.</Notice>}<p>{data.descricao}</p><div className="page-actions">{assetActions(data,auth.can).map(action=><button className={['baixar','inativar'].includes(action)?'btn danger':'btn secondary'} key={action} onClick={()=>open(action,data)}>{titles[action]}</button>)}<Link className="btn secondary" to={`/ativos/${id}/ficha`}>Ficha do ativo</Link></div></Card><Card className="asset-history"><h2>Histórico do ativo</h2><ResourceView resource={history}>{h=><>{records(h.content)}<Pagination page={h} setPage={setHistoryPage}/></>}</ResourceView></Card></>:<Card>{kind==='ativos'?<DataTable rows={data.content} columns={[{key:'identificacao',label:'Ativo',render:a=><Link to={`/ativos/${a.id}`}>{a.codigoPatrimonial} · {a.nome}</Link>},{key:'status',label:'Status',render:a=><Badge value={a.status}/>},{key:'condicao',label:'Condição',render:a=><Badge value={a.condicao}/>},{key:'local',label:'Localização',render:a=><>{assetLocation(a,refs.data?.[1])}<br/><ContextDisplay value={a.contexto}/></>},{key:'custodia',label:'Responsável',render:a=>a.responsavelId?(refs.data?.[0].find(p=>p.id===a.responsavelId)?.nome||`Funcionário #${a.responsavelId}`):'—'},{key:'proximaInspecao',label:'Próxima inspeção'}]}/>:records(data.content)}<Pagination page={data} setPage={setPage}/></Card>}</ResourceView>
 {modal&&<Modal title={titles[modal.action]} busy={busy} onClose={close}><form onSubmit={save}>{modal.asset.id&&<section className="asset-operation-context"><strong>{modal.asset.codigoPatrimonial} · {modal.asset.nome}</strong><p>Condição atual: {assetLabel(modal.asset.condicao)} · {assetLabel(modal.asset.status)}</p><p>Origem atual: {assetLocation(modal.asset,refs.data?.[1])}</p><ContextDisplay value={modal.asset.contexto}/></section>}{modal.action==='receber'&&<ResourceView resource={pending}>{r=>r&&<Notice>Confirmar chegada ao destino: {r.localDestinoNome||'Obra'} <ContextDisplay value={r.contextoDestino}/></Notice>}</ResourceView>}<Notice error>{error}</Notice>{attempt&&<Notice>A confirmação pode ter sido recebida. Confira o histórico antes de iniciar outra operação. {attempt.key?'Você pode reenviar esta mesma confirmação.':'Feche e confira a listagem; o cadastro não tem reenvio idempotente.'}</Notice>}<fieldset className="form-section" disabled={busy||!!attempt}>{'ativoId' in form&&!modal.asset.id&&<Field label="Pesquisar ativo para selecionar"><input value={assetTerm} onChange={e=>setAssetTerm(e.target.value)}/></Field>}{'ativoId' in form&&!modal.asset.id&&choices.data&&!choices.data.last&&<Notice>Mais de 100 ativos. Refine a pesquisa ou abra o detalhe do ativo na listagem.</Notice>}<ResourceView resource={refs}>{([people,warehouses,categories])=>{
  const person=(key,label)=><Field label={label}><select required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Selecionar funcionário</option>{people.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field>
  const warehouse=(required=false)=><Field label={modal.action==='devolver'?'Destino da devolução (opcional)':'Almoxarifado de destino'}><select required={required} value={form.almoxarifadoId||''} onChange={e=>setForm({...form,almoxarifadoId:e.target.value,...(modal.action==='transferir'?{contexto:{}}:{})})}><option value="">{modal.action==='devolver'?'Retornar ao local de origem':'Selecionar destino / usar Obra'}</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.nome}</option>)}</select></Field>
  return <div className="form-grid">{['criar','editar'].includes(modal.action)?<>{Object.entries({codigoPatrimonial:'Código patrimonial (vazio gera FER)',nome:'Nome do ativo',fabricante:'Fabricante',modelo:'Modelo',numeroSerie:'Número de série',dataAquisicao:'Data de aquisição'}).map(([k,label])=><Field key={k} label={label}><input required={k==='nome'} disabled={k==='codigoPatrimonial'&&modal.action==='editar'} maxLength={k==='codigoPatrimonial'?50:160} type={k==='dataAquisicao'?'date':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label="Categoria"><select value={form.categoriaId||''} onChange={e=>setForm({...form,categoriaId:e.target.value})}><option value="">Sem categoria</option>{categories.filter(c=>c.ativo||String(c.id)===String(form.categoriaId)).map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></Field><Field label="Descrição"><textarea maxLength={2000} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></Field>{modal.action==='criar'&&warehouse(true)}</>:<>{'ativoId' in form&&<Field label="Ativo"><select required disabled={!!modal.asset.id} value={form.ativoId} onChange={e=>{const selected=choices.data?.content.find(a=>String(a.id)===e.target.value);setForm({...form,ativoId:e.target.value,condicao:selected?.condicao||'BOM',...(modal.action==='emprestar'?{contexto:selected?.contexto?{obraId:selected.contexto.obraId,ordemServicoId:selected.contexto.ordemServicoId,centroCustoId:selected.contexto.centroCustoId}:{}}:{})})}}><option value="">Selecionar ativo</option>{(modal.asset.id?[modal.asset]:choices.data?.content||[]).filter(a=>modal.asset.id||assetActions(a,auth.can).includes(modal.action)).map(a=><option key={a.id} value={a.id}>{a.codigoPatrimonial} · {a.nome}</option>)}</select></Field>}{'entreguePorId' in form&&person('entreguePorId','Quem entregou')}{'funcionarioId' in form&&person('funcionarioId','Funcionário que recebeu')}{'devolvidoPorId' in form&&person('devolvidoPorId','Quem devolveu')}{'recebidoPorId' in form&&person('recebidoPorId','Quem recebeu')}{'inspetorId' in form&&person('inspetorId','Inspetor operacional')}{'responsavelId' in form&&person('responsavelId','Responsável operacional')}{'almoxarifadoId' in form&&warehouse()}</>}
  {'condicao' in form&&<Field label="Condição confirmada"><select required value={form.condicao} onChange={e=>setForm({...form,condicao:e.target.value})}>{conditions.map(v=><option key={v} value={v}>{assetLabel(v)}</option>)}</select></Field>}{'resultado' in form&&<Field label="Resultado da inspeção"><select value={form.resultado} onChange={e=>setForm({...form,resultado:e.target.value})}>{['APROVADO','APROVADO_COM_RESSALVA','REPROVADO'].map(v=><option key={v} value={v}>{assetLabel(v)}</option>)}</select></Field>}{['previsaoDevolucao','proximaInspecao'].filter(k=>k in form).map(k=><Field key={k} label={k==='previsaoDevolucao'?'Previsão de devolução':'Próxima inspeção'}><input type="date" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label={'motivo' in form?'Motivo obrigatório':'Observações / divergência'}><textarea required={'motivo' in form} maxLength={2000} value={form.motivo??form.observacao} onChange={e=>setForm({...form,['motivo' in form?'motivo':'observacao']:e.target.value})}/></Field>
 </div>}}</ResourceView>{'contexto' in form&&<details className="asset-context-options" open={modal.action==='transferir'||!!form.contexto?.obraId||!!form.contexto?.ordemServicoId||!!form.contexto?.centroCustoId}><summary>Contexto de Obra / OS / centro de custo (opcional)</summary><ContextSelector value={form.contexto} onChange={v=>setForm({...form,contexto:v,...(modal.action==='transferir'?{almoxarifadoId:''}:{})})}/></details>}<p>Confirme a condição e os responsáveis físicos. O usuário autenticado será registrado separadamente.</p></fieldset><div className="dialog-actions"><button type="button" className="btn secondary" disabled={busy} onClick={close}>Fechar</button><button className="btn" disabled={busy||!!attempt&&!attempt.key||modal.action==='receber'&&(pending.loading||!!pending.error||!pending.data)}>{busy?'Confirmando…':attempt?.key?'Reenviar mesma confirmação':'Confirmar operação'}</button></div></form></Modal>}</>
}
