import {useCallback,useState} from 'react'
import {Link,useParams,useLocation} from 'react-router-dom'
import {api} from '../api/client'
import {useAuth} from '../auth/AuthContext'
import {useResource} from '../hooks/useResource'
import {PageHeader,Card,ResourceView,DataTable,Field,Notice,dateTime} from '../components/ui'
import {Pagination} from './Suppliers'
import ContextSelector,{ContextDisplay} from '../components/ContextSelector'
import {epiLabel,epiAlerts} from '../utils/epis'
export function EpiItemTable({rows}){return <DataTable rows={rows} columns={[{key:'item',label:'EPI',render:i=><div className="cell-detail"><strong>{i.produtoCodigo} · {i.produtoNome}</strong><small>{[i.modelo,i.tamanho,i.lote].filter(Boolean).join(' · ')}</small></div>},{key:'action',label:'Operação',render:i=><>{i.entrega?'Entregue':'Encerrado'}{i.origemItemId&&<small className="epi-line-note">Origem: item #{i.origemItemId}</small>}</>},{key:'quantidade',label:'Quantidade',render:i=>`${i.quantidade} ${i.unidade}`},{key:'ca',label:'CA histórico',render:i=><>{i.ca}<small className="epi-line-note">{i.validadeCa||'Prazo não informado'}</small></>},{key:'validadeFisica',label:'Validade / troca',render:i=><>{i.validadeFisica||'Validade não informada'}<small className="epi-line-note">Trocar até: {i.substituirAte||'Sem prazo'}</small>{epiAlerts(i).map(a=><small className="epi-alert" key={a}>{a}</small>)}</>},{key:'context',label:'Contexto',render:i=><ContextDisplay value={i.contexto}/>},{key:'condition',label:'Condição / destino',render:i=><>{epiLabel(i.condicao)}<small className="epi-line-note">{epiLabel(i.destino)}</small></>},{key:'movimento',label:'Rastreabilidade',render:i=>i.movimentoId?<Link to={`/movimentacoes?produtoId=${i.produtoId}`}>Movimento #{i.movimentoId}</Link>:'Sem retorno ao estoque'}]}/>}
export default function EpiDeliveries(){
 const {id}=useParams(),location=useLocation(),auth=useAuth(),[filters,setFilters]=useState({funcionarioId:'',produtoId:'',ca:'',tipo:'',almoxarifadoId:'',de:'',ate:'',obraId:'',ordemServicoId:'',centroCustoId:''}),[page,setPage]=useState(0),[productTerm,setProductTerm]=useState(''),[chosenProduct,setChosenProduct]=useState(null)
 const refs=useResource(useCallback(signal=>Promise.all([api.list('funcionarios',{},signal),api.list('almoxarifados',{},signal)]),[]))
 const products=useResource(useCallback(signal=>id?Promise.resolve([]):api.searchProducts({termo:productTerm},signal),[id,productTerm]))
 const resource=useResource(useCallback(signal=>id?api.get('epi-entregas',id,signal):api.list('epi-entregas',{...filters,pagina:page},signal),[id,filters,page]))
 const filter=(k,v)=>{setFilters(f=>({...f,[k]:v}));setPage(0)}
 return <><PageHeader eyebrow="SEGURANÇA / SST" title={id?'Detalhe da entrega / registro':'Entregas de EPI'} description="Entrega, substituição, devolução e descarte com histórico preservado.">{id?<Link className="btn secondary" to="/epi-entregas">Voltar ao histórico</Link>:auth.can('EPI_ENTREGA_GERENCIAR')&&<Link className="btn" to="/epi-entregas/nova">Nova entrega</Link>}</PageHeader><Notice>{location.state?.success}</Notice>{!id&&<Card><div className="filters"><ResourceView resource={refs}>{([people,warehouses])=><><Field label="Filtrar funcionário"><select value={filters.funcionarioId} onChange={e=>filter('funcionarioId',e.target.value)}><option value="">Todos</option>{people.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field><Field label="Filtrar almoxarifado"><select value={filters.almoxarifadoId} onChange={e=>filter('almoxarifadoId',e.target.value)}><option value="">Todos</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.nome}</option>)}</select></Field></>}</ResourceView><Field label="Pesquisar produto no histórico"><input value={productTerm} onChange={e=>setProductTerm(e.target.value)}/></Field><ResourceView resource={products}>{rows=><Field label="Filtrar produto"><select value={filters.produtoId} onChange={e=>{filter('produtoId',e.target.value);setChosenProduct(rows.find(p=>String(p.id)===e.target.value)||null)}}><option value="">Todos</option>{(chosenProduct&&!rows.some(p=>p.id===chosenProduct.id)?[chosenProduct,...rows]:rows).map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.nome}</option>)}</select></Field>}</ResourceView><Field label="Filtrar CA histórico"><input value={filters.ca} onChange={e=>filter('ca',e.target.value)}/></Field><Field label="Filtrar tipo"><select value={filters.tipo} onChange={e=>filter('tipo',e.target.value)}><option value="">Todos</option>{['ENTREGA','SUBSTITUICAO','DEVOLUCAO','DESCARTE'].map(v=><option value={v} key={v}>{epiLabel(v)}</option>)}</select></Field><Field label="Data inicial"><input type="date" value={filters.de} onChange={e=>filter('de',e.target.value)}/></Field><Field label="Data final"><input type="date" value={filters.ate} onChange={e=>filter('ate',e.target.value)}/></Field>{filters.funcionarioId&&<Link className="btn secondary" to={'/epi-funcionarios/'+filters.funcionarioId}>Ficha de EPI do funcionário</Link>}<details className="asset-context-options"><summary>Filtrar por Obra / OS / centro de custo</summary><ContextSelector filter value={filters} onChange={v=>{setFilters(f=>({...f,...v}));setPage(0)}}/></details></div></Card>}
 <ResourceView resource={resource}>{r=>id?<><Card className="epi-section"><h2>Registro #{r.id} · {epiLabel(r.tipo)}</h2><dl className="document-metadata">{[['Funcionário',`${r.funcionarioNome} · ${r.funcionarioMatricula||'Sem matrícula'}`],['Data / hora',dateTime(r.dataHora)],['Almoxarifado',r.almoxarifadoNome],['Responsável operacional',r.responsavelNome],['Usuário autenticado',r.atorNome],['Motivo',epiLabel(r.motivo)],['Confirmação',r.recebimentoConfirmado?'Recebimento operacional confirmado':'Encerramento operacional registrado']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><ContextDisplay value={r.contexto}/><p className="asset-observation">{r.observacao}</p><div className="dialog-actions"><Link className="btn secondary" to={'/epi-funcionarios/'+r.funcionarioId}>Ficha do funcionário</Link><Link className="btn" to={`/epi-entregas/${r.id}/documento`}>Comprovante do registro</Link></div></Card><Card><EpiItemTable rows={r.itens}/></Card></>:<Card><EpiHistory rows={r.content}/><Pagination page={r} setPage={setPage}/></Card>}</ResourceView></>
}
export function EpiHistory({rows}){return <DataTable rows={rows} columns={[{key:'id',label:'Registro',render:r=><Link to={'/epi-entregas/'+r.id}>#{r.id} · {epiLabel(r.tipo)}</Link>},{key:'funcionarioNome',label:'Funcionário',render:r=><Link to={'/epi-funcionarios/'+r.funcionarioId}>{r.funcionarioNome}</Link>},{key:'dataHora',label:'Data / hora',render:r=>dateTime(r.dataHora)},{key:'itens',label:'EPIs / CA',render:r=>r.itens.map(i=><small className="epi-line-note" key={i.id}>{i.produtoNome} · {i.quantidade} {i.unidade} · CA {i.ca} · {i.entrega?'Entrega':'Encerramento'}</small>)},{key:'context',label:'Contexto',render:r=><ContextDisplay value={r.contexto}/>},{key:'responsavelNome',label:'Responsável'},{key:'document',label:'Documento',render:r=><Link to={`/epi-entregas/${r.id}/documento`}>Comprovante #{r.id}</Link>}]}/>}
