import {useCallback,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {api} from '../api/client'
import {useResource} from '../hooks/useResource'
import {ResourceView,dateTime} from '../components/ui'
import OperationalDocument from '../components/OperationalDocument'
import {ContextDisplay} from '../components/ContextSelector'
import {epiLabel} from '../utils/epis'
export default function EpiDocument(){const {id}=useParams(),[generated]=useState(()=>dateTime(new Date().toISOString())),resource=useResource(useCallback(signal=>api.get('epi-entregas',id,signal),[id]));return <main className="document-view"><ResourceView resource={resource}>{r=><><nav className="document-actions"><Link className="btn secondary" to={'/epi-entregas/'+id}>Voltar ao registro</Link><button className="btn" onClick={()=>window.print()}>Imprimir / salvar PDF</button></nav><OperationalDocument title={r.tipo==='ENTREGA'||r.tipo==='SUBSTITUICAO'?'Ficha de entrega de EPI':'Comprovante de '+epiLabel(r.tipo).toLowerCase()+' de EPI'} reference={'EPI-'+r.id} generatedAt={generated} metadata={[["Funcionário",r.funcionarioNome],["Matrícula",r.funcionarioMatricula],["Data / hora",dateTime(r.dataHora)],["Tipo / motivo",epiLabel(r.tipo)+' · '+epiLabel(r.motivo)],["Almoxarifado",r.almoxarifadoNome],["Responsável operacional",r.responsavelNome],["Usuário autenticado",r.atorNome],["Confirmação",r.recebimentoConfirmado?'Recebimento declarado pelo operador autenticado':'Encerramento registrado pelo operador autenticado']]}><div><ContextDisplay value={r.contexto}/></div><table className="epi-document-table"><thead><tr><th>EPI / identificação</th><th>Quantidade</th><th>CA / prazo</th><th>Validade / troca</th></tr></thead><tbody>{r.itens.map(i=><tr key={i.id}><td><strong>{i.produtoNome}</strong><br/>{i.produtoCodigo} · {i.tamanho||'Sem variação'}<br/>{[i.fabricante,i.modelo,i.lote].filter(Boolean).join(' · ')}<br/>{i.entrega?'Entrega':'Encerramento'} · item #{i.id}{i.origemItemId&&<> · origem #{i.origemItemId}</>}<br/><ContextDisplay value={i.contexto}/>{!i.entrega&&<><br/>{epiLabel(i.condicao)} · {epiLabel(i.destino)}</>}{i.observacao&&<p className="asset-observation">{i.observacao}</p>}</td><td>{i.quantidade} {i.unidade}</td><td>{i.ca}<br/>{i.validadeCa||'Não informado'}</td><td>Fabricação: {i.fabricacao||'—'}<br/>Validade física: {i.validadeFisica||'—'}<br/>Troca recomendada: {i.substituirAte||'—'}</td></tr>)}</tbody></table><p className="asset-observation">{r.observacao}</p><p className="document-note">Registro operacional com identificação e dados históricos. Confirmação registrada pelo usuário autenticado, sem assinatura jurídica do funcionário. CA e validade física são conceitos distintos. Este documento não atesta aptidão do funcionário ou conformidade legal de SST.</p></OperationalDocument></>}</ResourceView></main>}
