import {useCallback,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {api,request} from '../api/client'
import {useAuth} from '../auth/AuthContext'
import {useResource} from '../hooks/useResource'
import {PageHeader,Card,ResourceView,DataTable,Field,Modal,Notice,Badge} from '../components/ui'
import {Pagination} from './Suppliers'
const blank={produtoId:'',ca:'',fabricante:'',modelo:'',tamanho:'',validadeCa:'',diasSubstituicao:'',ativo:true,exigeDevolucao:false,permiteRetorno:false,observacao:''}
export default function Epis(){
 const auth=useAuth(),sending=useRef(false),[filters,setFilters]=useState({termo:'',ca:'',ativo:''}),[page,setPage]=useState(0),[form,setForm]=useState(null),[editing,setEditing]=useState(null),[productTerm,setProductTerm]=useState(''),[chosenProduct,setChosenProduct]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const resource=useResource(useCallback(signal=>api.list('epis',{...filters,pagina:page},signal),[filters,page]))
 const products=useResource(useCallback(signal=>form&&!editing?api.searchProducts({termo:productTerm,ativo:true},signal):Promise.resolve([]),[!!form,editing,productTerm]))
 const change=(k,v)=>setForm(f=>({...f,[k]:v}))
 async function save(e){e.preventDefault();if(sending.current)return;sending.current=true;setBusy(true);setError('');try{const body={...form,produtoId:Number(form.produtoId),validadeCa:form.validadeCa||null,diasSubstituicao:form.diasSubstituicao?Number(form.diasSubstituicao):null};await request('/epis'+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body});setForm(null);setSuccess('Configuração de EPI salva.');resource.reload()}catch(e){setError(e.message)}finally{sending.current=false;setBusy(false)}}
 const filter=(k,v)=>{setFilters(f=>({...f,[k]:v}));setPage(0)}
 return <><PageHeader eyebrow="SEGURANÇA / SST" title="EPIs" description="Metadados de proteção vinculados ao catálogo e ao estoque existentes.">{auth.can('EPI_GERENCIAR')&&<button className="btn" onClick={()=>{setEditing(null);setChosenProduct(null);setProductTerm('');setForm({...blank});setError('');setSuccess('')}}>Configurar EPI</button>}<Link className="btn secondary" to="/epi-entregas">Entregas e histórico</Link></PageHeader><Notice>{success}</Notice><Card className="epi-config-list"><div className="filters"><Field label="Pesquisar EPIs"><input value={filters.termo} onChange={e=>filter('termo',e.target.value)} placeholder="Código, nome ou CA"/></Field><Field label="Filtrar CA"><input value={filters.ca} onChange={e=>filter('ca',e.target.value)}/></Field><Field label="Situação do EPI"><select value={filters.ativo} onChange={e=>filter('ativo',e.target.value)}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></Field></div><ResourceView resource={resource}>{p=><><DataTable rows={(p.content||[]).map(e=>({...e,id:e.produtoId}))} columns={[{key:'nome',label:'EPI / produto',render:e=><div className="cell-detail"><strong>{e.nome}</strong><small>{e.codigo} · {e.unidade}</small></div>},{key:'ca',label:'CA',render:e=><><strong>{e.ca}</strong><small className="epi-line-note">{e.validadeCa||'Prazo não informado'}{e.caVencido?' · prazo cadastrado vencido':''}</small></>},{key:'tamanho',label:'Variação',render:e=>[e.modelo,e.tamanho].filter(Boolean).join(' · ')||'—'},{key:'ativo',label:'Situação',render:e=><><Badge value={e.ativo}/>{!e.produtoAtivo&&<small className="epi-line-note">Produto inativo</small>}</>},{key:'policy',label:'Devolução / retorno',render:e=><>{e.exigeDevolucao?'Devolução requerida':'Sem obrigação de devolução'}<small className="epi-line-note">{e.permiteRetorno?'Retorno condicionado permitido':'Sem retorno ao estoque'}</small></>},{key:'actions',label:'Ações',render:e=>auth.can('EPI_GERENCIAR')&&<button className="btn text" onClick={()=>{setEditing(e.produtoId);setForm(Object.fromEntries(Object.keys(blank).map(k=>[k,e[k]??blank[k]])));setError('')}}>Editar {e.nome}</button>}]}/><Pagination page={p} setPage={setPage}/></>}</ResourceView></Card>
 <p className="epi-help">CA identifica o modelo cadastrado. Validade física é registrada na entrega. Estes dados não representam avaliação de conformidade de SST.</p>
 {form&&<Modal trapFocus title={editing?'Editar configuração de EPI':'Configurar EPI'} busy={busy} onClose={()=>!busy&&setForm(null)}><form className="epi-form" onSubmit={save}><Notice error>{error}</Notice><fieldset disabled={busy} className="form-section"><div className="form-grid">{!editing&&<><Field label="Pesquisar produto"><input value={productTerm} onChange={e=>setProductTerm(e.target.value)}/></Field><ResourceView resource={products}>{rows=><Field label="Produto do catálogo"><select required value={form.produtoId} onChange={e=>{change('produtoId',e.target.value);setChosenProduct(rows.find(p=>String(p.id)===e.target.value)||null)}}><option value="">Selecionar produto</option>{(chosenProduct&&!rows.some(p=>p.id===chosenProduct.id)?[chosenProduct,...rows]:rows).map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.nome}</option>)}</select></Field>}</ResourceView></>}{[['ca','CA','text',20],['fabricante','Fabricante','text',160],['modelo','Modelo','text',160],['tamanho','Tamanho / numeração','text',50],['validadeCa','Validade cadastrada do CA','date'],['diasSubstituicao','Recomendação de troca (dias)','number']].map(([k,label,type,max])=><Field key={k} label={label}><input type={type} required={k==='ca'} maxLength={max} min={type==='number'?1:undefined} max={type==='number'?36500:undefined} value={form[k]} onChange={e=>change(k,e.target.value)}/></Field>)}{[['ativo','EPI ativo'],['exigeDevolucao','Exige devolução'],['permiteRetorno','Permite retorno condicionado ao estoque']].map(([k,label])=><Field key={k} label={label}><select value={String(form[k])} onChange={e=>change(k,e.target.value==='true')}><option value="true">Sim</option><option value="false">Não</option></select></Field>)}<Field label="Observações"><textarea maxLength={2000} value={form.observacao} onChange={e=>change('observacao',e.target.value)}/></Field></div><p>CA, modelo e tamanho não podem mudar com saldo físico positivo. Para variantes simultâneas, use produtos distintos. Retorno exige conferência explícita; não significa liberação automática de reutilização.</p></fieldset><div className="dialog-actions"><button type="button" className="btn secondary" disabled={busy} onClick={()=>setForm(null)}>Fechar</button><button className="btn" disabled={busy}>{busy?'Salvando…':'Salvar configuração'}</button></div></form></Modal>}</>
}
