import { useCallback, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import { useResource } from '../hooks/useResource'
import { PageHeader, Card, DataTable, ResourceView, Badge, quantity, dateTime, Notice } from '../components/ui'
import { filterNeeds } from '../utils/fulfillment'
import { unitLabel } from '../utils/operations'
export default function PurchaseNeeds() {
  const [params] = useSearchParams()
  const [status, setStatus] = useState(''), [product, setProduct] = useState(''), [warehouse, setWarehouse] = useState(''), [requestId, setRequestId] = useState(params.get('solicitacaoId') || ''), [term, setTerm] = useState('')
  const resource = useResource(useCallback(signal => api.purchaseNeeds({ status, produtoId: product, almoxarifadoId: warehouse, solicitacaoId: requestId }, signal), [status, product, warehouse, requestId]))
  const refs = useResource(useCallback(signal => Promise.all(['produtos', 'almoxarifados'].map(name => api.list(name, null, signal))), []))
  const options = rows => (rows || []).map(row => <option key={row.id} value={row.id}>{row.nome}</option>)
  return <><PageHeader eyebrow="OPERAÇÃO" title="Necessidades de compra" description="Faltas confirmadas a partir das solicitações. Não representam pedidos de compra."><button className="btn secondary" onClick={resource.reload}>Atualizar</button></PageHeader><Card><div className="filters"><input type="search" aria-label="Pesquisar necessidades" placeholder="Código, material, solicitação…" value={term} onChange={e => setTerm(e.target.value)}/><select aria-label="Filtrar status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos os status</option>{['ABERTA', 'ATENDIDA', 'CANCELADA'].map(s => <option key={s}>{s}</option>)}</select><select aria-label="Filtrar produto" value={product} onChange={e => setProduct(e.target.value)}><option value="">Todos os produtos</option>{options(refs.data?.[0])}</select><select aria-label="Filtrar almoxarifado" value={warehouse} onChange={e => setWarehouse(e.target.value)}><option value="">Todos os almoxarifados</option>{options(refs.data?.[1])}</select><input type="number" min="1" aria-label="Filtrar solicitação" placeholder="Solicitação" value={requestId} onChange={e => setRequestId(e.target.value)}/></div><Notice error>{refs.error?.message}</Notice><ResourceView resource={resource}>{rows => <DataTable empty="Nenhuma necessidade encontrada." rows={filterNeeds(rows, term)} columns={[{ key: 'id', label: 'Necessidade', render: n => `#${n.id}` }, { key: 'codigo', label: 'Código', render: n => n.produto?.codigo || '—' }, { key: 'material', label: 'Material', render: n => n.produto?.nome }, { key: 'quantidade', label: 'Falta registrada', render: n => `${quantity(n.quantidade)} ${unitLabel(n.produto)}` }, { key: 'local', label: 'Almoxarifado', render: n => n.almoxarifado?.nome }, { key: 'status', label: 'Status', render: n => <Badge value={n.status}/> }, { key: 'data', label: 'Registrada em', render: n => dateTime(n.dataHora) }, { key: 'responsavel', label: 'Responsável', render: n => n.responsavel?.nome }, { key: 'solicitacao', label: 'Origem', render: n => <Link to={`/solicitacoes?solicitacaoId=${n.solicitacaoId}`}>Solicitação #{n.solicitacaoId}</Link> }]}/>}</ResourceView></Card></>
}
