import { useCallback } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { useResource } from '../hooks/useResource'
import { ResourceView, dateTime, quantity } from '../components/ui'
import OperationalDocument from '../components/OperationalDocument'
import { money } from '../utils/purchases'
export default function PurchaseDocument({ receipt = false }) {
 const { id } = useParams()
 const resource = useResource(useCallback(() => api.get(receipt ? 'recebimentos-compra' : 'pedidos-compra', id), [id, receipt]))
 return <div className="document-view purchase-document"><ResourceView resource={resource}>{data => <><nav className="document-actions"><Link className="btn secondary" to={`/pedidos-compra/${receipt ? data.pedidoId : id}`}>Voltar ao pedido</Link><button className="btn" onClick={() => window.print()}>Imprimir / salvar PDF</button></nav><OperationalDocument title={receipt ? 'Comprovante de recebimento' : 'Pedido de compra'} reference={receipt ? `REC-${data.id} · ${data.pedidoNumero}` : data.numero} generatedAt={dateTime(new Date().toISOString())} metadata={receipt ? [['Pedido', data.pedidoNumero], ['Fornecedor', data.fornecedorNome], ['Destino', data.almoxarifadoNome], ['Recebido em', dateTime(data.dataHora)], ['Responsável físico', data.responsavelNome], ['Usuário autenticado', data.recebidoPorNome]] : [['Fornecedor', data.fornecedorNome], ['Documento do fornecedor', data.fornecedorDocumento], ['Contato', data.fornecedorContato], ['Destino', data.almoxarifadoNome], ['Estado do pedido', data.status], ['Criado por', `${data.criadoPorNome} · ${dateTime(data.criadoEm)}`], ['Aprovado por', data.aprovadoPorNome ? `${data.aprovadoPorNome} · ${dateTime(data.aprovadoEm)}` : 'Aguardando aprovação'], ['Valor total', money(data.total)]]}><div className="document-table-scroll" tabIndex={0} aria-label="Itens do documento; role a tabela para consultar as colunas"><table className="document-table"><thead><tr><th>Código / material</th><th>Un.</th><th>{receipt ? 'Recebido' : 'Pedido'}</th>{receipt ? <><th>Saldo anterior</th><th>Saldo posterior</th></> : <><th>Valor unitário</th><th>Subtotal</th></>}<th>Origem / destinação</th></tr></thead><tbody>{data.itens.map(i => <tr key={i.id}><td><strong>{i.codigo}</strong><br/>{i.nome}</td><td>{i.unidade || '—'}</td><td>{quantity(i.quantidade)}</td>{receipt ? <><td>{quantity(i.saldoAnterior)}</td><td>{quantity(i.saldoPosterior)}</td></> : <><td>{money(i.valorUnitario)}</td><td>{money(i.subtotal)}</td></>}<td>{(receipt ? i.destinacoes : i.alocacoes).map(a => <p key={a.necessidadeId}>Necessidade #{a.necessidadeId} · Solicitação #{a.solicitacaoId} · {quantity(a.quantidade)}</p>)}{!receipt && i.quantidadeEstoque > 0 && <p>{quantity(i.quantidadeEstoque)} para estoque</p>}{receipt && !i.destinacoes.length && 'Estoque'}</td></tr>)}</tbody></table></div>{data.observacao && <section><h2>Observações</h2><p>{data.observacao}</p></section>}<p className="document-note">{receipt ? 'Confirmação física registrada com usuário autenticado. O atendimento da solicitação ocorre em etapa posterior.' : 'A aprovação autoriza a compra. A entrada de estoque exige confirmação física de recebimento.'}</p><p className="document-note">Registro interno: {receipt ? `/recebimentos-compra/${id}` : `/pedidos-compra/${id}`} · acesso autenticado e sujeito a permissões.</p></OperationalDocument></>}</ResourceView></div>
}
