import { Link } from 'react-router-dom'
import { useCallback, useState } from 'react'
import { api, request } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { useResource } from '../hooks/useResource'
import { PageHeader, Card, ResourceView, DataTable, Badge, Notice, Modal, Field } from '../components/ui'
export function Pagination({ page, setPage }) { return <div className="page-actions"><span>{page.totalElements || 0} registros · Página {(page.number || 0) + 1} de {Math.max(1, page.totalPages || 1)}</span><button className="btn secondary" disabled={page.first} onClick={() => setPage(page.number - 1)}>Anterior</button><button className="btn secondary" disabled={page.last} onClick={() => setPage(page.number + 1)}>Próxima</button></div> }
const empty = { nome: '', nomeFantasia: '', tipoPessoa: 'PJ', documento: '', email: '', telefone: '', contato: '', observacao: '', ativo: true }
export default function Suppliers() {
 const auth = useAuth(), [termo, setTerm] = useState(''), [documento, setDocument] = useState(''), [ativo, setActive] = useState(''), [pagina, setPage] = useState(0), [form, setForm] = useState(null), [id, setId] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
 const resource = useResource(useCallback(signal => api.list('fornecedores', { termo, documento, ativo, pagina }, signal), [termo, documento, ativo, pagina]))
 async function edit(row) { setError(''); try { const value = await api.get('fornecedores', row.id); setForm(Object.fromEntries(Object.keys(empty).map(key => [key, value[key] ?? empty[key]]))); setId(row.id) } catch(e) { setError(e.message) } }
 async function save(event) { event.preventDefault(); if(busy)return; setBusy(true); setError(''); try { await request(`/fornecedores${id ? '/' + id : ''}`, { method: id ? 'PUT' : 'POST', body: form }); setForm(null); resource.reload() } catch(e) { setError(e.message) } finally { setBusy(false) } }
 const field = (key, label, type = 'text', max = 160) => <Field label={label}><input type={type} maxLength={max} required={key === 'nome'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></Field>
 return <><PageHeader eyebrow="COMPRAS" title="Fornecedores" description="Cadastros de pessoas físicas e jurídicas, com histórico preservado.">{auth.can('FORNECEDOR_GERENCIAR') && <button className="btn" onClick={() => { setId(null); setForm({ ...empty }); setError('') }}>Novo fornecedor</button>}</PageHeader><Notice error>{error}</Notice><Card><div className="filters"><input aria-label="Pesquisar fornecedores" placeholder="Nome ou nome fantasia" value={termo} onChange={e => { setTerm(e.target.value); setPage(0) }}/><input aria-label="Filtrar documento" placeholder="CPF / CNPJ" value={documento} onChange={e => { setDocument(e.target.value); setPage(0) }}/><select aria-label="Filtrar fornecedores ativos" value={ativo} onChange={e => { setActive(e.target.value); setPage(0) }}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></div><ResourceView resource={resource}>{page => <><DataTable rows={page.content || []} columns={[{ key: 'nome', label: 'Nome' }, { key: 'nomeFantasia', label: 'Nome fantasia' }, { key: 'tipoPessoa', label: 'Tipo' }, { key: 'documento', label: 'Documento protegido' }, { key: 'ativo', label: 'Situação', render: f => <Badge value={f.ativo}/> }, { key: 'history', label: 'Histórico', render: f => <Link to={`/pedidos-compra?fornecedorId=${f.id}`}>Compras e preços</Link> }, { key: 'actions', label: 'Cadastro', render: f => auth.can('FORNECEDOR_GERENCIAR') && <button className="btn text" onClick={() => edit(f)}>Editar {f.nome}</button> }]}/><Pagination page={page} setPage={setPage}/></>}</ResourceView></Card>{form && <Modal title={id ? 'Editar fornecedor' : 'Novo fornecedor'} busy={busy} onClose={() => setForm(null)}><form onSubmit={save}><div className="form-grid">{field('nome', 'Nome / razão social *')}{field('nomeFantasia', 'Nome fantasia')}<Field label="Tipo de pessoa *"><select value={form.tipoPessoa} onChange={e => setForm({ ...form, tipoPessoa: e.target.value })}><option value="PJ">Pessoa jurídica</option><option value="PF">Pessoa física</option></select></Field>{field('documento', 'CPF / CNPJ (opcional)', 'text', 30)}{field('email', 'Email', 'email')}{field('telefone', 'Telefone', 'tel', 40)}{field('contato', 'Contato', 'text', 120)}<Field label="Situação"><select value={String(form.ativo)} onChange={e => setForm({ ...form, ativo: e.target.value === 'true' })}><option value="true">Ativo</option><option value="false">Inativo</option></select></Field><Field label="Observação"><textarea maxLength={1000} value={form.observacao} onChange={e => setForm({ ...form, observacao: e.target.value })}/></Field></div><Notice error>{error}</Notice><div className="dialog-actions"><button type="button" className="btn secondary" disabled={busy} onClick={() => setForm(null)}>Cancelar</button><button className="btn" disabled={busy}>{busy ? 'Salvando…' : 'Salvar fornecedor'}</button></div></form></Modal>}</>
}
