import { useCallback, useState } from 'react'
import { request } from '../api/client'
import { useResource } from '../hooks/useResource'
import { PageHeader, Card, DataTable, ResourceView, Modal, Field, Notice } from '../components/ui'
export default function Users(){
 const resource=useResource(useCallback(signal=>request('/usuarios',{signal}),[])),[editing,setEditing]=useState(null),[reset,setReset]=useState(null),[notice,setNotice]=useState('')
 const done=message=>{setEditing(null);setReset(null);setNotice(message);resource.reload()}
 return <><PageHeader eyebrow="ADMINISTRAÇÃO" title="Usuários" description="Identidades de acesso. Funcionários permanecem um cadastro separado."><button className="btn" onClick={()=>setEditing({username:'',nomeExibicao:'',perfil:'CONSULTA',ativo:true,funcionarioId:''})}>Novo usuário</button></PageHeader><Notice>{notice}</Notice><Card><ResourceView resource={resource}>{rows=><DataTable rows={rows} columns={[{key:'username',label:'Usuário'},{key:'nomeExibicao',label:'Nome'},{key:'perfil',label:'Perfil'},{key:'ativo',label:'Situação',render:u=>u.ativo?'Ativo':'Inativo'},{key:'actions',label:'Ações',render:u=><div className="table-actions"><button className="btn text" onClick={()=>setEditing(u)}>Editar usuário</button><button className="btn text" onClick={()=>setReset(u)}>Redefinir senha</button></div>}]}/>}</ResourceView></Card>{editing&&<UserForm initial={editing} onClose={()=>setEditing(null)} onSaved={done}/>} {reset&&<PasswordReset user={reset} onClose={()=>setReset(null)} onSaved={done}/>}</>
}
function UserForm({initial,onClose,onSaved}){
 const [form,setForm]=useState({...initial,password:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const people=useResource(useCallback(signal=>request('/funcionarios',{signal}),[]))
 const change=(key,value)=>setForm(f=>({...f,[key]:value}))
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const body={username:form.username,nomeExibicao:form.nomeExibicao,perfil:form.perfil,ativo:form.ativo,funcionarioId:form.funcionarioId?Number(form.funcionarioId):null};if(!form.id)body.password=form.password;await request('/usuarios'+(form.id?'/'+form.id:''),{method:form.id?'PUT':'POST',body});setForm(f=>({...f,password:''}));onSaved('Usuário salvo com sucesso.')}catch(cause){setError(cause.message)}finally{setBusy(false)}}
 return <Modal title={form.id?'Editar usuário':'Novo usuário'} busy={busy} onClose={onClose}><form onSubmit={save}><Notice error>{error}</Notice><div className="form-grid"><Field label="Usuário"><input required maxLength={80} autoComplete="off" value={form.username} onChange={e=>change('username',e.target.value)}/></Field><Field label="Nome de exibição"><input required maxLength={120} value={form.nomeExibicao} onChange={e=>change('nomeExibicao',e.target.value)}/></Field><Field label="Perfil"><select value={form.perfil} onChange={e=>change('perfil',e.target.value)}>{['CONSULTA','ALMOXARIFE','GESTOR','ADMIN'].map(p=><option key={p}>{p}</option>)}</select></Field><Field label="Funcionário vinculado (opcional)"><select value={form.funcionarioId||''} onChange={e=>change('funcionarioId',e.target.value)}><option value="">Sem vínculo</option>{(people.data||[]).map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field><Field label="Usuário ativo"><input type="checkbox" checked={form.ativo} onChange={e=>change('ativo',e.target.checked)}/></Field>{!form.id&&<Field label="Senha inicial" hint="Ao menos 10 caracteres; máximo de 72 bytes UTF-8."><input type="password" autoComplete="new-password" required minLength={10} value={form.password} onChange={e=>change('password',e.target.value)}/></Field>}</div><Notice error>{people.error?.message}</Notice><div className="form-actions"><button className="btn secondary" type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="btn" disabled={busy||people.loading}>{busy?'Salvando…':'Salvar usuário'}</button></div></form></Modal>
}
function PasswordReset({user,onClose,onSaved}){const [password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');try{await request('/usuarios/'+user.id+'/senha',{method:'PUT',body:{password}});setPassword('');onSaved('Senha redefinida. Sessões anteriores serão invalidadas.')}catch(cause){setError(cause.message)}finally{setBusy(false)}}return <Modal title="Redefinir senha" onClose={onClose} busy={busy}><form onSubmit={submit}><p>Usuário: {user.username}. As sessões anteriores serão invalidadas.</p><Notice error>{error}</Notice><Field label="Nova senha" hint="Ao menos 10 caracteres; máximo de 72 bytes UTF-8."><input type="password" autoComplete="new-password" required minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/></Field><div className="form-actions"><button className="btn secondary" type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="btn" disabled={busy}>{busy?'Redefinindo…':'Confirmar redefinição'}</button></div></form></Modal>}
