import { AuthProvider, Protected } from './auth/AuthContext'
import Login from './auth/Login'
import Users from './pages/Users'
import PurchaseNeeds from './pages/PurchaseNeeds'
import SeparationList from './pages/SeparationList'
import { Routes, Route, Navigate, Link } from 'react-router-dom'
import AppShell from './components/AppShell'
import Dashboard from './pages/Dashboard'
import Products from './pages/Products'
import Transfers from './pages/Transfers'
import Registries from './pages/Registries'
import { Stocks, Requests, Movements } from './pages/Operations'
export default function App(){return <AuthProvider><Routes><Route path="login" element={<Login/>}/><Route element={<Protected/>}><Route path="solicitacoes/:id/lista-separacao" element={<SeparationList/>}/><Route element={<AppShell/>}><Route index element={<Navigate to="/dashboard" replace/>}/><Route path="usuarios" element={<Users/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="produtos" element={<Products/>}/><Route path="categorias" element={<Registries key="categorias" name="categorias"/>}/><Route path="unidades" element={<Registries key="unidades" name="unidades-medida"/>}/><Route path="almoxarifados" element={<Registries key="almoxarifados" name="almoxarifados"/>}/><Route path="funcionarios" element={<Registries key="funcionarios" name="funcionarios"/>}/><Route path="estoques" element={<Stocks/>}/><Route path="solicitacoes" element={<Requests/>}/><Route path="necessidades-compra" element={<PurchaseNeeds/>}/><Route path="transferencias" element={<Transfers/>}/><Route path="movimentacoes" element={<Movements/>}/><Route path="*" element={<div className="state"><p className="eyebrow">404</p><h1>Página não encontrada</h1><p>O endereço informado não corresponde a uma página da BES.</p><Link to="/dashboard" className="btn">Ir para o dashboard</Link></div>}/></Route></Route></Routes></AuthProvider>}
