import Structure from './pages/Structure'
import ServiceOrderDocument from './pages/ServiceOrderDocument'
import Suppliers from './pages/Suppliers'
import PurchaseOrders from './pages/PurchaseOrders'
import PurchaseDocument from './pages/PurchaseDocument'
import { AuthProvider, Protected } from './auth/AuthContext'
import Login from './auth/Login'
import Users from './pages/Users'
import PurchaseNeeds from './pages/PurchaseNeeds'
import SeparationList from './pages/SeparationList'
import { Routes, Route, Navigate, Link } from 'react-router-dom'
import AppShell from './components/AppShell'
import Dashboard from './pages/Dashboard'
import Products from './pages/Products'
import Transfers from './pages/Transfers'
import Registries from './pages/Registries'
import { Stocks, Requests, Movements } from './pages/Operations'
export default function App(){return <AuthProvider><Routes><Route path="login" element={<Login/>}/><Route element={<Protected/>}><Route path="ordens-servico/:id/documento" element={<ServiceOrderDocument/>}/><Route path="pedidos-compra/:id/documento" element={<PurchaseDocument/>}/><Route path="recebimentos-compra/:id/documento" element={<PurchaseDocument receipt/>}/><Route path="solicitacoes/:id/lista-separacao" element={<SeparationList/>}/><Route element={<AppShell/>}><Route index element={<Navigate to="/dashboard" replace/>}/><Route path="obras" element={<Structure key="obras" kind="obras"/>}/><Route path="obras/:id" element={<Structure key="obras-detail" kind="obras"/>}/><Route path="ordens-servico" element={<Structure key="ordens-servico" kind="ordens-servico"/>}/><Route path="ordens-servico/:id" element={<Structure key="ordens-servico-detail" kind="ordens-servico"/>}/><Route path="centros-custo" element={<Structure key="centros-custo" kind="centros-custo"/>}/><Route path="centros-custo/:id" element={<Structure key="centros-custo-detail" kind="centros-custo"/>}/><Route path="usuarios" element={<Users/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="produtos" element={<Products/>}/><Route path="categorias" element={<Registries key="categorias" name="categorias"/>}/><Route path="unidades" element={<Registries key="unidades" name="unidades-medida"/>}/><Route path="almoxarifados" element={<Registries key="almoxarifados" name="almoxarifados"/>}/><Route path="funcionarios" element={<Registries key="funcionarios" name="funcionarios"/>}/><Route path="estoques" element={<Stocks/>}/><Route path="solicitacoes" element={<Requests/>}/><Route path="fornecedores" element={<Suppliers/>}/><Route path="pedidos-compra" element={<PurchaseOrders/>}/><Route path="pedidos-compra/:id" element={<PurchaseOrders/>}/><Route path="necessidades-compra" element={<PurchaseNeeds/>}/><Route path="transferencias" element={<Transfers/>}/><Route path="movimentacoes" element={<Movements/>}/><Route path="*" element={<div className="state"><p className="eyebrow">404</p><h1>Página não encontrada</h1><p>O endereço informado não corresponde a uma página da BES.</p><Link to="/dashboard" className="btn">Ir para o dashboard</Link></div>}/></Route></Route></Routes></AuthProvider>}
